https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py
# Module 1: _What_ is PyTorch?
---
<dl>
    <dt>PyTorch</dt>
    <dd>is a Python-based computing package</dd>
</dl>

- A programming language that uses the power of GPU's to speed up calculations.
> I don't have an <font color=green>NVIDIA GPU</font> at the moment but I'll press on.
>
> I'll rent one here -> [NVIDIA GPU in the clouds above](https://cloud.google.com/)
- It's flexible and F.A.S.T.
    > `Python` + "...dang it's so fast it lit a <font color=red>_Torch_</font>" == __`PyTorch`__


## Getting Started
### Tensors

As I discovered in the first tutorial, `PyTorch` is similar to` NumPy`. Again, `PyTorch` uses __GPU's__, which makes it faster than `NumPy` for deep learning.

In [1]:
from __future__ import print_function
import torch
import numpy as np

> "An __uninitialized matrix__ is declared, but _does not_ contain __definite known values__ before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values."

### Creating an empty Tensor

In [2]:
# Creating an 'uninitialized matrix' with `tensor.empty()`
# So does it not have values?
x = torch.empty(5, 3)
print(x)

tensor([[-9.2973e-15,  4.5905e-41, -9.2973e-15],
        [ 4.5905e-41,  0.0000e+00,  4.6566e-10],
        [ 0.0000e+00,  4.6566e-10,  7.0065e-45],
        [ 0.0000e+00,  5.3824e-36,  1.4013e-45],
        [-9.5253e-15,  4.5905e-41,  0.0000e+00]])


In [3]:
# Interesting, the "values" (0's) that were placed in the empty tensor matrix
# changed to actual values once operated on...
x + 1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

### Creating a Random Martrix

In [4]:
# torch.randn?

In [5]:
x = torch.randn(5, 7, dtype=torch.float64)
print(x)

tensor([[-1.0758,  0.9682, -0.8631, -1.4730,  0.6766, -1.1055,  0.6607],
        [ 1.4250,  1.0929,  0.3821,  0.2489,  1.8766, -0.5388, -2.1219],
        [ 0.6043,  0.5990, -0.9361, -1.7533,  0.4821,  1.3970,  0.3425],
        [-1.3889,  0.5857, -2.4046,  0.7792,  0.7658,  0.9115, -2.3788],
        [-1.0766,  1.1045,  0.0713, -2.0370, -0.3341, -0.4171,  2.0965]],
       dtype=torch.float64)


### Creating a Matrix of Zeros and Ones

https://pytorch.org/docs/stable/tensors.html

In [6]:
torch.zeros(5, 5, dtype=torch.long)  # 64-bit integer (signed)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [7]:
torch.zeros(5, 5, dtype=torch.bool)

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

In [8]:
torch.ones(5, 5, dtype=torch.float64)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

In [9]:
torch.ones(5, 5, dtype=torch.bool)

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [10]:
torch.ones(3, 3, dtype=torch.cdouble)

tensor([[1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j]], dtype=torch.complex128)

#### Notes
PyTorch tensors are unable to infer True as 1 and False as 0's
``` python
torch.ones(5, 5, dtype=torch.bool).mean()
```
<font color=red>RuntimeError</font>: Can only calculate the mean of floating types. Got Bool instead.


### Create a Tensor from Data

In [11]:
# Create a Tensor using NumPy to generate data
x = torch.tensor(np.random.randint(1, 11, size=(10, 10)))

# Create a Tensor using PyTorch built in method `.randint()`
y = torch.randint(1, 11, size=(10, 10))

In [40]:
print(x.dtype)
x

torch.int64


tensor([[ 2,  8,  2,  9,  6,  6,  9,  9,  8,  9],
        [10, 10,  5,  3,  6,  9,  9,  1,  6,  8],
        [ 2, 10,  6,  4,  3,  2,  8,  3,  3,  8],
        [ 3,  4,  2,  5,  9,  1,  5,  3,  4,  4],
        [ 4,  6, 10,  4,  2,  1,  8,  9,  2,  1],
        [ 2,  3,  5,  4, 10,  9,  1,  7,  1,  3],
        [ 8,  5,  3,  2,  8,  7,  3,  2,  5,  8],
        [ 9,  9,  8,  4,  4,  5,  2,  7,  6, 10],
        [ 9,  7,  9,  2,  6,  6,  8,  5,  5,  5],
        [ 7,  5,  8,  8,  4,  9,  9,  4,  8,  8]])

In [41]:
print(y.dtype)
y

torch.int64


tensor([[ 6,  9,  5,  3,  1,  2,  6,  5,  3,  7],
        [ 4,  1,  8,  1,  1,  6,  8,  7,  9,  5],
        [ 5,  9,  6,  2, 10, 10,  4,  2,  4, 10],
        [ 9,  9,  9,  9,  5,  9,  2,  8,  5,  1],
        [ 8,  7,  2,  2,  1,  2,  2,  6,  9,  6],
        [ 6,  7,  4,  8,  2,  8,  4,  7,  8, 10],
        [ 1,  8,  5,  6,  6,  9,  9,  9,  1,  2],
        [ 1,  2,  8,  7, 10,  8,  5,  3, 10,  4],
        [ 8,  1,  8,  5,  1,  3,  5,  3,  4,  6],
        [10,  7, 10,  2,  3,  3,  2,  9,  8,  8]])

### Create a Tensor based on an existing Tensor
#### Creating Tensors with new dimensions, dtypes, and requires_grad

In [42]:
# Using .new_*() methods, we can create new Tensors!
# If needed, we can also change the dtype

new_x1 = x.new_ones(3, 3)
new_x2 = x.new_ones(5, 5, dtype=torch.double)

In [43]:
print(new_x1.dtype)
new_x1

torch.int64


tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [44]:
print(new_x2.dtype)
new_x2

torch.float64


tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

The newly created Tensors do not have `requires_grad=True` because:
1. The original Tensor it was created from did not have `requires_grad=True`
2. When creating the Tensor from an exisiting Tensor, __WE__ did not specifiy `requires_grad=True`.

>__REMINDER__! `requires_grad=True` can only be set on Tensors of `dtype=float`!
> Example:
> ``` python
> # new_x1.dtype >>> torch.int64
new_x1.requires_grad_()
> ```
> If you try to set `requires_grad=True` on a Tensor of dtype `torch.int64` you'll get the following error.
>
> <font color=red>RuntimeError</font>:
>```python 
Only Tensors of float point dtype can require gradients
```

In [17]:
print(new_x1.requires_grad)
print(new_x2.requires_grad)

False
False


In [18]:
# print(new_x1.requires_grad_())

# Now our new tensor has memory.
print(new_x2.requires_grad_())

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64, requires_grad=True)


### Creating Tensors from Tensors using the SAME dimensions, different dtypes, requires_grad

In [36]:
# x was initialized with the data type `int`
x_new_full = x.new_full(x.shape, 10, dtype=float).requires_grad_()
y_new_full = x.new_full(x.size(), 10, dtype=float).requires_grad_()

In [39]:
print(x.shape)
print(x.size())
print(x.dtype)

torch.Size([10, 10])
torch.Size([10, 10])
torch.int64


In [45]:
print('x')
print(x_new_full.shape)
print(x_new_full.dtype)

print('\ny')
print(y_new_full.shape)
print(y_new_full.dtype)

x
torch.Size([10, 10])
torch.float64

y
torch.Size([10, 10])
torch.float64


### Operations

In [49]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)

In [50]:
print(x + y)

tensor([[1.0693, 0.4115, 1.1077],
        [1.0523, 0.9651, 0.3075],
        [0.2645, 1.6528, 1.3218],
        [0.8017, 0.5093, 0.5735],
        [0.1091, 1.2219, 1.3482]])


In [51]:
print(torch.add(x, y))

tensor([[1.0693, 0.4115, 1.1077],
        [1.0523, 0.9651, 0.3075],
        [0.2645, 1.6528, 1.3218],
        [0.8017, 0.5093, 0.5735],
        [0.1091, 1.2219, 1.3482]])


In [52]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.0693, 0.4115, 1.1077],
        [1.0523, 0.9651, 0.3075],
        [0.2645, 1.6528, 1.3218],
        [0.8017, 0.5093, 0.5735],
        [0.1091, 1.2219, 1.3482]])


In [53]:
y.add_(x)

tensor([[1.0693, 0.4115, 1.1077],
        [1.0523, 0.9651, 0.3075],
        [0.2645, 1.6528, 1.3218],
        [0.8017, 0.5093, 0.5735],
        [0.1091, 1.2219, 1.3482]])

In [54]:
y

tensor([[1.0693, 0.4115, 1.1077],
        [1.0523, 0.9651, 0.3075],
        [0.2645, 1.6528, 1.3218],
        [0.8017, 0.5093, 0.5735],
        [0.1091, 1.2219, 1.3482]])

In [55]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.shape, z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [61]:
x = torch.randint(1, 11, size=(3, 3))

In [66]:
print(x)
x[0,0].item()

tensor([[ 2,  4,  4],
        [ 3,  6,  1],
        [ 7, 10,  4]])


2

### NumPy Bridge
Converting a Torch Tensor to a NumPy array and vice a versa.

In [67]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [70]:
b = a.numpy()
print(b)
print(b.dtype)

[1. 1. 1. 1. 1.]
float32


In [71]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [72]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

Converting a NumPy Array to Torch Tensor

In [73]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [74]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!


In [75]:
torch.device("cpu")

device(type='cpu')

In [76]:
torch.device("cuda")

device(type='cuda')

In [77]:
torch.cuda.is_available()

False

# Module 2 Differentation through Autograd

# Module 3 Training a Neural Network by Defining a Neural Network

# Module 4 Train a Classifier