# Introduction to Pytorch
https://pytorch.org/tutorials/beginner/nlp/pytorch_tutorial.html

Notes:
- Deep learning uses __tensors__ to perform computations.

In [2]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import pandas as pd

torch.manual_seed(1);

## Creating Tensors
$\vec{v}$ to $\mathcal{T}$

https://en.wikiversity.org/wiki/Tensors/Definitions

https://pytorch.org/docs/stable/tensors.html

__Tensors__ can be constructed using:
1. List of lists
1. `pandas` series
1. `numpy` 1D-arrays
1. List of numbers in `Python`.

In [3]:
# My first lil tensor :')
torch.tensor(1)

tensor(1)

Create a Tensor from a Python list

In [4]:
data = list(range(0, 10))

In [5]:
vector = torch.tensor(data)

Create a Tensor Matrix from:
1. List of lists
1. List of Series
1. `numpy` matrix
1. `pandas` matrix

In [53]:
# List of lists
lists = [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]

torch.tensor(lists)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [64]:
# List of Series
a = pd.Series(np.arange(0, 10))

torch.tensor((a, a, a))

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [23]:
# numpy matrix
matrix_A = np.random.uniform(1, 10, size=(3,3))

torch.tensor(matrix_A)

tensor([[4.6373, 7.9764, 4.7976],
        [3.2350, 8.9028, 1.1303],
        [7.0170, 5.8797, 4.0584]], dtype=torch.float64)

In [51]:
# pandas matrix
matrix_B = pd.DataFrame(
    np.random.randint(low=1,high=100,size=(10,10))
)

# torch.as_tensor(matrix_B) >>> TypeError: not a sequence
# torch.tensor(martix_B) >>> TypeError: not a sequence
torch.tensor(matrix_B.values)

tensor([[47,  5, 15, 92, 23, 32, 70, 83, 82, 17],
        [33, 32, 90, 84, 87, 84, 18, 80, 70, 90],
        [94,  5, 49, 95, 32,  5, 71, 50,  2, 40],
        [18,  2, 71, 76,  6, 60, 71, 25,  2, 22],
        [21, 64, 33, 41, 85,  9, 40, 40, 10, 42],
        [34, 14, 14, 66, 15, 31, 33, 90, 56,  7],
        [64, 52,  6, 29, 11, 10, 94, 95, 30, 81],
        [65, 21, 60, 52, 22, 61, 21, 85, 59, 21],
        [56, 61, 70, 16, 71, 82, 85, 25,  3, 29],
        [76, 93,  7, 45, 26, 64, 67, 22, 71, 12]])

Create a multi-dimensional Tensor from:
1. List of lists
1. List of Series
1. `numpy` matrix
1. `pandas` matrix

In [65]:
# List of lists
multi_lists = [[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]]]

torch.tensor(multi_lists)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [60]:
torch.tensor?

In [66]:
a = pd.Series(np.arange(0, 10))

# torch.tensor((a, b, c).as_matrix())
# torch.cat((a, b, c))

torch.tensor(a)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Tests

``` python
np.ndarray(vector) # tensors do not support indexing error.
np.array(vector)
pd.Series(vector)
pd.DataFrame(vector)
```

In [67]:
T = torch.arange(0, 10_000_000).reshape(1000, 100, 100)
M = np.arange(0, 10_000_000).reshape(1000, 100, 100)

In [76]:
%%timeit -r 10 -n 1_000
1 + T

15.4 ms ± 337 µs per loop (mean ± std. dev. of 10 runs, 1000 loops each)


In [77]:
%%timeit -r 10 -n 1_000
1 + M

16.8 ms ± 143 µs per loop (mean ± std. dev. of 10 runs, 1000 loops each)
