# Introduction to Pytorch
https://pytorch.org/tutorials/beginner/nlp/pytorch_tutorial.html

Notes:
- Deep learning uses __tensors__ to perform computations.

In [13]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import pandas as pd

torch.manual_seed(1);

## Creating Tensors
$\vec{v}$ to $\mathcal{T}$

https://en.wikiversity.org/wiki/Tensors/Definitions

https://pytorch.org/docs/stable/tensors.html

__Tensors__ can be constructed using:
1. List of lists
1. `pandas` series
1. `numpy` 1D-arrays
1. List of numbers in `Python`.

In [14]:
# My first lil tensor :')
torch.tensor(1)

tensor(1)

Create a Tensor from a Python list

In [15]:
data = list(range(0, 10))

In [16]:
vector = torch.tensor(data)

Create a Tensor Matrix from:
1. List of lists
1. List of Series
1. `numpy` matrix
1. `pandas` matrix

In [17]:
# List of lists
lists = [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]

torch.tensor(lists)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
# List of Series
a = pd.Series(np.arange(0, 10))

torch.tensor((a, a, a))

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [19]:
# numpy matrix
matrix_A = np.random.uniform(1, 10, size=(3,3))

torch.tensor(matrix_A)

tensor([[9.6162, 9.6506, 4.9820],
        [6.7036, 4.2751, 2.8464],
        [3.9134, 1.0935, 9.3289]], dtype=torch.float64)

In [20]:
# pandas matrix
matrix_B = pd.DataFrame(
    np.random.randint(low=1,high=100,size=(10,10))
)

# torch.as_tensor(matrix_B) >>> TypeError: not a sequence
# torch.tensor(martix_B) >>> TypeError: not a sequence
torch.tensor(matrix_B.values)

tensor([[54, 79, 79,  7, 19, 61, 38, 84, 57, 94],
        [44, 76, 69, 29, 49,  3, 22,  1, 72, 96],
        [44, 13, 27,  4, 78, 31, 81, 10, 52, 36],
        [63, 50, 66, 16, 75, 34, 94, 45, 19, 71],
        [39, 44, 91, 96, 11, 88, 86, 23, 63, 26],
        [ 2, 43, 66, 57, 55, 39, 85, 72, 69,  3],
        [16, 97, 30, 60, 70, 60, 71, 92, 43, 70],
        [38, 61, 32, 72, 50, 95, 87, 30, 99, 12],
        [11, 68, 72, 36, 95, 54, 29, 20, 53, 50],
        [71, 76, 23, 37, 99, 66, 19, 56, 28,  8]])

Create a multi-dimensional Tensor from:

1. List of lists
2. List of Series
3. `numpy` matrix
4. `pandas` matrix

In [28]:
# List of lists
multi_lists = [[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]]]

torch.tensor(multi_lists).shape

torch.Size([3, 3, 3])

What is a multi-dimesional (n-D) tensor?

1. A multi-dimesional tensor has matrix indicies
2. A matrix has vector indicies
3. A vector has scalar indicies

Let's look at this visually, starting with the vector we created, $\vec{v}$ vector.

In [31]:
print(vector.shape)
print(vector)

torch.Size([10])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


__Plain English__:

We have an array with 10 numbers

The shape of the array is 10 rows x 1 column

__Explanation__:

We're working with a vector with 10 elements. The elements are _scalars_ with values 0 - 9.
> Elements in _linear algebra_ are also called entries, coefficients, or components.

> 1. Elements of a vector
2. Entries of a vector
3. Coefficients of a vector
4. Components of a vector

> To explain this difference between _elements_ and _scalars_, let's imagine you're sitting down to a nice breakfast with your family. 

>There's pancakes, sausage, toast, yogurt, fruit, bacon, tea, coffee, orange juice, and water. Like a vulture, you circle each platter for the perfect piece and add it to your plate. Once you're finished you take a seat.

> 1. Your _plate is the vector_. It holds your delicious breakfast.
2. Each piece of fresh food you have on your plate is the _number of elements in your vector_.
3. The __name__ of each piece(s) (e.g. 3 strips of bacon, 2 pieces of fruit, 1 dallop of yogurt, 4 pancakes) are your _scalars_!

>Food for thought: You have a preference, the pieces on your plate are the direct result of weighted decisions _you make_.

>Let's make our plate:

>$\vec{plate}$ = \[3 bacon, 2 fruit, 1 yogurt, 4 pancakes\]

>Awesome. Now let's not forget about our computer's breakfast, I mean vector:

>$\vec{v}$ = \[3, 2, 1, 4\]

> Help your family out by washing those dishes :)

In [29]:
vector[0]

tensor(0)

In [27]:
# torch.tensor?

In [23]:
a = pd.Series(np.arange(0, 10))

# torch.tensor((a, b, c).as_matrix())
# torch.cat((a, b, c))

torch.tensor(a)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Tests

``` python
np.ndarray(vector) # tensors do not support indexing error.
np.array(vector)
pd.Series(vector)
pd.DataFrame(vector)
```

In [24]:
T = torch.arange(0, 10_000_000).reshape(1000, 100, 100)
M = np.arange(0, 10_000_000).reshape(1000, 100, 100)

In [25]:
%%timeit -r 10 -n 1_000
1 + T

16.2 ms ± 491 µs per loop (mean ± std. dev. of 10 runs, 1000 loops each)


In [26]:
%%timeit -r 10 -n 1_000
1 + M

16.5 ms ± 282 µs per loop (mean ± std. dev. of 10 runs, 1000 loops each)
