# Module 1: _What_ is PyTorch?
---
[Source](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py) for this tutorial

<br></br>
<dl>
    <dt>PyTorch</dt>
    <dd>is a Python-based computing package</dd>
</dl>

- A programming language that uses the power of GPU's to speed up calculations.
> I don't have an <font color=green>NVIDIA GPU</font> at the moment but I'll press on.
>
> I'll rent one here -> [NVIDIA GPU in the clouds above](https://cloud.google.com/)
- It's flexible and F.A.S.T.
    > `Python` + "...dang it's so fast it lit a <font color=red>_Torch_</font>" == __`PyTorch`__


## Getting Started
### Tensors

As I discovered in the first tutorial, `PyTorch` is similar to` NumPy`. Again, `PyTorch` uses __GPU's__, which makes it faster than `NumPy` for deep learning.

In [1]:
from __future__ import print_function
import torch
import numpy as np

> "An __uninitialized matrix__ is declared, but _does not_ contain __definite known values__ before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values."

### Creating an empty Tensor

In [2]:
# Creating an 'uninitialized matrix' with `tensor.empty()`
# So does it not have values?
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 6.4954e-32,  1.4013e-45, -1.8362e-13],
        [ 4.5883e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00, -8.5899e+09,  4.2800e+35]])


In [3]:
# Interesting, the "values" (0's) that were placed in the empty tensor matrix
# changed to actual values once operated on...
x + 1

tensor([[ 1.0000e+00,  1.0000e+00,  1.0000e+00],
        [ 1.0000e+00,  1.0000e+00,  1.0000e+00],
        [ 1.0000e+00,  1.0000e+00,  1.0000e+00],
        [ 1.0000e+00,  1.0000e+00,  1.0000e+00],
        [ 1.0000e+00, -8.5899e+09,  4.2800e+35]])

### Creating a Random Martrix

In [4]:
# torch.randn?

In [5]:
x = torch.randn(5, 7, dtype=torch.float64)
print(x)

tensor([[ 2.3101e+00, -2.1743e-03, -1.4070e+00,  2.6794e-01, -6.4896e-01,
          6.6472e-01, -5.1099e-01],
        [ 4.1534e-02,  1.9102e+00,  9.2398e-01,  1.7829e+00,  3.2493e-03,
          8.8165e-02,  7.0458e-01],
        [-3.0569e-01, -5.2556e-02,  7.5630e-01,  5.3482e-01, -6.5294e-01,
         -2.2294e+00, -6.8318e-02],
        [ 1.2900e+00, -2.8512e-01, -7.3142e-01,  2.4426e+00,  9.9655e-01,
          3.2386e-01, -7.2284e-01],
        [ 1.9928e+00, -1.2711e+00,  2.6694e-01,  3.6880e-01,  2.8421e-01,
          5.1292e-01,  9.2426e-01]], dtype=torch.float64)


### Creating a Matrix of Zeros and Ones

https://pytorch.org/docs/stable/tensors.html

In [6]:
torch.zeros(5, 5, dtype=torch.long)  # 64-bit integer (signed)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [7]:
torch.zeros(5, 5, dtype=torch.bool)

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

In [8]:
torch.ones(5, 5, dtype=torch.float64)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

In [9]:
torch.ones(5, 5, dtype=torch.bool)

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [10]:
torch.ones(3, 3, dtype=torch.cdouble)

tensor([[1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j]], dtype=torch.complex128)

#### Notes
PyTorch tensors are unable to infer True as 1 and False as 0's
``` python
torch.ones(5, 5, dtype=torch.bool).mean()
```
<font color=red>RuntimeError</font>: Can only calculate the mean of floating types. Got Bool instead.


### Create a Tensor from Data

In [11]:
# Create a Tensor using NumPy to generate data
x = torch.tensor(np.random.randint(1, 11, size=(10, 10)))

# Create a Tensor using PyTorch built in method `.randint()`
y = torch.randint(1, 11, size=(10, 10))

In [12]:
print(x.dtype)
x

torch.int64


tensor([[ 2,  3,  6, 10,  3,  2, 10,  2,  4,  4],
        [ 1,  4,  5,  1,  6,  6,  3,  2,  1,  1],
        [ 4,  5,  1,  3,  3, 10,  6,  2,  7,  7],
        [ 1,  6, 10,  9,  3,  2,  3,  7,  3,  5],
        [ 1,  8,  8,  2,  5,  4,  3,  2,  7,  2],
        [ 3,  1,  3, 10,  7,  5,  7,  7,  4,  2],
        [ 3, 10,  2,  7,  2, 10,  3,  3, 10,  4],
        [ 1,  7,  8,  5,  4,  3,  8,  3,  6,  2],
        [ 8,  6,  9,  7,  5,  4,  3,  2, 10,  9],
        [ 2,  9,  3,  5,  5,  9,  2,  2,  5,  4]])

In [13]:
print(y.dtype)
y

torch.int64


tensor([[ 8,  8,  6,  9,  9, 10,  5, 10,  5,  4],
        [ 5,  6,  3,  7,  4,  7, 10,  2,  3,  4],
        [10,  3, 10,  3,  3,  3,  9,  8,  2,  3],
        [10,  6,  9,  4,  4,  6,  5,  6,  2,  8],
        [ 2,  1,  2,  8,  4,  1,  3,  4,  7,  5],
        [ 9,  9,  9,  8,  2,  8,  8,  9,  2,  6],
        [ 2,  2, 10,  6,  2,  8,  2,  5,  2,  2],
        [ 5,  6,  1,  1,  5, 10,  1,  6, 10,  7],
        [ 9, 10,  6,  2,  3,  2,  8,  7,  5,  7],
        [ 5,  3,  7,  4,  7,  9,  2, 10,  9,  1]])

### Create a Tensor based on an existing Tensor
#### Creating Tensors with new dimensions, dtypes, and requires_grad

In [14]:
# Using .new_*() methods, we can create new Tensors!
# If needed, we can also change the dtype

new_x1 = x.new_ones(3, 3)
new_x2 = x.new_ones(5, 5, dtype=torch.double)

In [15]:
print(new_x1.dtype)
new_x1

torch.int64


tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [16]:
print(new_x2.dtype)
new_x2

torch.float64


tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

The newly created Tensors do not have `requires_grad=True` because:
1. The original Tensor it was created from did not have `requires_grad=True`
2. When creating the Tensor from an exisiting Tensor, __WE__ did not specifiy `requires_grad=True`.

>__REMINDER__! `requires_grad=True` can only be set on Tensors of `dtype=float`!
> Example:
> ``` python
> # new_x1.dtype >>> torch.int64
new_x1.requires_grad_()
> ```
> If you try to set `requires_grad=True` on a Tensor of dtype `torch.int64` you'll get the following error.
>
> <font color=red>RuntimeError</font>:
>```python 
Only Tensors of float point dtype can require gradients
```

In [17]:
print(new_x1.requires_grad)
print(new_x2.requires_grad)

False
False


In [18]:
# print(new_x1.requires_grad_())

# Now our new tensor has memory.
print(new_x2.requires_grad_())

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64, requires_grad=True)


### Creating Tensors from Tensors using the SAME dimensions, different dtypes, requires_grad

In [19]:
# x was initialized with the data type `int`
x_new_full = x.new_full(x.shape, 10, dtype=float).requires_grad_()
y_new_full = x.new_full(x.size(), 10, dtype=float).requires_grad_()

In [20]:
print(x.shape)
print(x.size())
print(x.dtype)

torch.Size([10, 10])
torch.Size([10, 10])
torch.int64


In [21]:
print('x')
print(x_new_full.shape)
print(x_new_full.dtype)

print('\ny')
print(y_new_full.shape)
print(y_new_full.dtype)

x
torch.Size([10, 10])
torch.float64

y
torch.Size([10, 10])
torch.float64


### Operations

In [22]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)

In [23]:
print(x + y)

tensor([[0.8623, 0.8818, 0.4070],
        [1.3345, 0.3685, 0.9906],
        [1.1661, 1.1500, 1.2025],
        [0.4510, 1.3047, 1.1523],
        [0.5595, 1.0531, 0.7526]])


In [24]:
print(torch.add(x, y))

tensor([[0.8623, 0.8818, 0.4070],
        [1.3345, 0.3685, 0.9906],
        [1.1661, 1.1500, 1.2025],
        [0.4510, 1.3047, 1.1523],
        [0.5595, 1.0531, 0.7526]])


In [25]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.8623, 0.8818, 0.4070],
        [1.3345, 0.3685, 0.9906],
        [1.1661, 1.1500, 1.2025],
        [0.4510, 1.3047, 1.1523],
        [0.5595, 1.0531, 0.7526]])


In [26]:
y.add_(x)

tensor([[0.8623, 0.8818, 0.4070],
        [1.3345, 0.3685, 0.9906],
        [1.1661, 1.1500, 1.2025],
        [0.4510, 1.3047, 1.1523],
        [0.5595, 1.0531, 0.7526]])

In [27]:
y

tensor([[0.8623, 0.8818, 0.4070],
        [1.3345, 0.3685, 0.9906],
        [1.1661, 1.1500, 1.2025],
        [0.4510, 1.3047, 1.1523],
        [0.5595, 1.0531, 0.7526]])

In [28]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.shape, z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [29]:
x = torch.randint(1, 11, size=(3, 3))

In [30]:
print(x)
x[0,0].item()

tensor([[10,  7,  1],
        [ 1,  5, 10],
        [ 2,  7,  8]])


10

### NumPy Bridge
Converting a Torch Tensor to a NumPy array and vice a versa.

In [31]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [32]:
b = a.numpy()
print(b)
print(b.dtype)

[1. 1. 1. 1. 1.]
float32


In [33]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [34]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

Converting a NumPy Array to Torch Tensor

In [35]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [36]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!


In [37]:
torch.device("cpu")

device(type='cpu')

In [38]:
torch.device("cuda")

device(type='cuda')

In [39]:
torch.cuda.is_available()

False

# Module 2 Autograd: Automatic Differentiation
---
[Source](https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html) of this tutorial

PyTorch functions for auto-gradient implementation:
1. `torch.tensor`
1. `torch.tensor.requires_grad_()`
1. `torch.tensor.backward()`
1. `tensor.detach()`
1. `tensor.grad_fn`

The `autograd` package is the cornerstone to all neural networks in `PyTorch`.
- `autograd` provides automatic differentiation fot all operations on all tensors. MEMORY
- Backpropagation is defined by how your code is excuted.
- Every iteration can be different.

## Tensor
__`torch.tensor`__ is the fundamental building block in PyTorch.
> If `requires_grad=True`, the tensor begins to "remember" all operations on it.
>
> When you call `.backward()` on a `torch.tensor` object that has the attribute `requires_grad=True`, all gradients are computed automatically.
    > - The gradient is stored in the `.grad` attribute.

To remove a tensor's "memory" use `.detach()` to detach it from the computational history. Detach it from its "experience". The tensor will also not be able to "remember" any future computations performed on it.

To prevent a torch from having memory, wrap the code block with:
> `with torch.no_grad():`

Note: Useful when evaluating a model because the model may have "trainable parameters" with `requires_grad=True` and we __don't need the gradients__.

`Function`

In [49]:
x = torch.tensor([1, 2, 3], dtype=float, requires_grad=True)
y = torch.tensor([1, 2, 3], dtype=float, requires_grad=True)
z = x + y

In [54]:
z.grad_fn

# Module 3 Training a Neural Network by Defining a Neural Network

# Module 4 Train a Classifier