# Module 1: _What_ is PyTorch?
---
[Source](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py) for this tutorial

<br></br>
<dl>
    <dt>PyTorch</dt>
    <dd>is a Python-based computing package</dd>
</dl>

- A programming language that uses the power of GPU's to speed up calculations.
> I don't have an <font color=green>NVIDIA GPU</font> at the moment but I'll press on.
>
> I'll rent one here -> [NVIDIA GPU in the clouds above](https://cloud.google.com/)
- It's flexible and F.A.S.T.
    > `Python` + "...dang it's so fast it lit a <font color=red>_Torch_</font>" == __`PyTorch`__


## Getting Started
### Tensors

As I discovered in the first tutorial, `PyTorch` is similar to` NumPy`. Again, `PyTorch` uses __GPU's__, which makes it faster than `NumPy` for deep learning.

In [64]:
from __future__ import print_function
import torch
import numpy as np

> "An __uninitialized matrix__ is declared, but _does not_ contain __definite known values__ before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values."

### Creating an empty Tensor

In [65]:
# Creating an 'uninitialized matrix' with `tensor.empty()`
# So does it not have values?
x = torch.empty(5, 3)
print(x)

tensor([[1.6816e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [66]:
# Interesting, the "values" (0's) that were placed in the empty tensor matrix
# changed to actual values once operated on...
x + 1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

### Creating a Random Martrix

In [67]:
# torch.randn?

In [68]:
x = torch.randn(5, 7, dtype=torch.float64)
print(x)

tensor([[ 0.0916, -0.3037,  0.6995,  0.7574,  0.4234, -0.3557, -0.8298],
        [-0.2322,  0.6200,  0.3670,  1.0628,  0.1133, -1.2792, -0.0153],
        [ 1.6407, -1.1008, -2.5461, -1.7217,  0.8697,  1.6432, -0.5604],
        [-0.7609, -0.9253, -1.0508, -0.3378, -0.1354, -0.0995, -0.1097],
        [-0.9636,  0.3893,  0.6245, -0.0587,  1.9228, -1.3758,  1.3084]],
       dtype=torch.float64)


### Creating a Matrix of Zeros and Ones

https://pytorch.org/docs/stable/tensors.html

In [69]:
torch.zeros(5, 5, dtype=torch.long)  # 64-bit integer (signed)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [70]:
torch.zeros(5, 5, dtype=torch.bool)

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

In [71]:
torch.ones(5, 5, dtype=torch.float64)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

In [72]:
torch.ones(5, 5, dtype=torch.bool)

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [73]:
torch.ones(3, 3, dtype=torch.cdouble)

tensor([[1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j]], dtype=torch.complex128)

#### Notes
PyTorch tensors are unable to infer True as 1 and False as 0's
``` python
torch.ones(5, 5, dtype=torch.bool).mean()
```
<font color=red>RuntimeError</font>: Can only calculate the mean of floating types. Got Bool instead.


### Create a Tensor from Data

In [74]:
# Create a Tensor using NumPy to generate data
x = torch.tensor(np.random.randint(1, 11, size=(10, 10)))

# Create a Tensor using PyTorch built in method `.randint()`
y = torch.randint(1, 11, size=(10, 10))

In [75]:
print(x.dtype)
x

torch.int64


tensor([[ 6,  5, 10,  4,  2, 10,  9, 10,  9,  3],
        [ 5,  5,  6,  9,  4,  2,  3,  5, 10, 10],
        [ 3,  8,  5,  1,  4, 10,  1,  6,  3,  6],
        [ 3,  3,  2,  6,  9, 10,  3,  9,  5, 10],
        [ 4,  6,  6,  8,  9,  4,  1,  4,  6,  1],
        [ 5,  2,  3,  8,  2,  7,  5,  1, 10,  9],
        [ 8,  8, 10,  2,  7,  5,  4,  8,  9,  6],
        [ 2,  8,  1,  4,  7,  7, 10,  4,  4,  6],
        [ 5,  9,  2,  3,  6,  7,  6,  7,  3,  4],
        [ 9,  3,  5,  5,  4,  9, 10,  7, 10,  3]])

In [76]:
print(y.dtype)
y

torch.int64


tensor([[ 1,  1,  9,  5,  8,  8, 10,  6,  3,  9],
        [ 6, 10,  5,  8,  6,  2,  7,  8,  3,  1],
        [ 8, 10,  6,  5,  2,  4,  9,  2,  6,  1],
        [ 6,  3,  3, 10,  6, 10,  8,  7,  6,  7],
        [ 8,  6,  4,  8,  8,  2,  6,  8,  5,  8],
        [ 4,  4,  2,  1,  5,  5, 10,  7,  3,  1],
        [ 7,  3,  2,  5, 10,  5,  2,  5,  6,  4],
        [10,  6,  3,  4,  3,  1,  6,  3,  4,  4],
        [ 4,  5, 10,  2,  4,  9,  7,  8, 10, 10],
        [ 7,  4,  5,  9, 10,  8, 10,  2,  1,  8]])

### Create a Tensor based on an existing Tensor
#### Creating Tensors with new dimensions, dtypes, and requires_grad

In [77]:
# Using .new_*() methods, we can create new Tensors!
# If needed, we can also change the dtype

new_x1 = x.new_ones(3, 3)
new_x2 = x.new_ones(5, 5, dtype=torch.double)

In [78]:
print(new_x1.dtype)
new_x1

torch.int64


tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [79]:
print(new_x2.dtype)
new_x2

torch.float64


tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

The newly created Tensors do not have `requires_grad=True` because:
1. The original Tensor it was created from did not have `requires_grad=True`
2. When creating the Tensor from an exisiting Tensor, __WE__ did not specifiy `requires_grad=True`.

>__REMINDER__! `requires_grad=True` can only be set on Tensors of `dtype=float`!
> Example:
> ``` python
> # new_x1.dtype >>> torch.int64
new_x1.requires_grad_()
> ```
> If you try to set `requires_grad=True` on a Tensor of dtype `torch.int64` you'll get the following error.
>
> <font color=red>RuntimeError</font>:
>```python 
Only Tensors of float point dtype can require gradients
```

In [80]:
print(new_x1.requires_grad)
print(new_x2.requires_grad)

False
False


In [81]:
# print(new_x1.requires_grad_())

# Now our new tensor has memory.
print(new_x2.requires_grad_())

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64, requires_grad=True)


### Creating Tensors from Tensors using the SAME dimensions, different dtypes, requires_grad

In [82]:
# x was initialized with the data type `int`
x_new_full = x.new_full(x.shape, 10, dtype=float).requires_grad_()
y_new_full = x.new_full(x.size(), 10, dtype=float).requires_grad_()

In [83]:
print(x.shape)
print(x.size())
print(x.dtype)

torch.Size([10, 10])
torch.Size([10, 10])
torch.int64


In [84]:
print('x')
print(x_new_full.shape)
print(x_new_full.dtype)

print('\ny')
print(y_new_full.shape)
print(y_new_full.dtype)

x
torch.Size([10, 10])
torch.float64

y
torch.Size([10, 10])
torch.float64


### Operations

In [85]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)

In [86]:
print(x + y)

tensor([[0.8623, 1.4138, 0.5886],
        [1.0883, 1.5882, 1.2020],
        [0.6420, 0.5145, 1.4439],
        [0.5153, 1.1107, 1.2614],
        [1.2066, 0.7039, 1.4612]])


In [87]:
print(torch.add(x, y))

tensor([[0.8623, 1.4138, 0.5886],
        [1.0883, 1.5882, 1.2020],
        [0.6420, 0.5145, 1.4439],
        [0.5153, 1.1107, 1.2614],
        [1.2066, 0.7039, 1.4612]])


In [88]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.8623, 1.4138, 0.5886],
        [1.0883, 1.5882, 1.2020],
        [0.6420, 0.5145, 1.4439],
        [0.5153, 1.1107, 1.2614],
        [1.2066, 0.7039, 1.4612]])


In [89]:
y.add_(x)

tensor([[0.8623, 1.4138, 0.5886],
        [1.0883, 1.5882, 1.2020],
        [0.6420, 0.5145, 1.4439],
        [0.5153, 1.1107, 1.2614],
        [1.2066, 0.7039, 1.4612]])

In [90]:
y

tensor([[0.8623, 1.4138, 0.5886],
        [1.0883, 1.5882, 1.2020],
        [0.6420, 0.5145, 1.4439],
        [0.5153, 1.1107, 1.2614],
        [1.2066, 0.7039, 1.4612]])

In [91]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.shape, z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [92]:
x = torch.randint(1, 11, size=(3, 3))

In [93]:
print(x)
x[0,0].item()

tensor([[10,  6,  2],
        [ 9,  4,  4],
        [ 8, 10,  1]])


10

### NumPy Bridge
---
Converting a Torch Tensor to a NumPy array and vice a versa.

In [94]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [95]:
b = a.numpy()
print(b)
print(b.dtype)

[1. 1. 1. 1. 1.]
float32


In [96]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [97]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

Converting a NumPy Array to Torch Tensor

In [98]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [99]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!


In [100]:
torch.device("cpu")

device(type='cpu')

In [101]:
torch.device("cuda")

device(type='cuda')

In [102]:
torch.cuda.is_available()

False

# Module 2 Autograd: Automatic Differentiation
---
[Source](https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html) of this tutorial

PyTorch functions for auto-gradient implementation:
1. `torch.tensor`
1. `torch.tensor.requires_grad_()`
1. `torch.tensor.backward()`
1. `tensor.detach()`
1. `tensor.grad_fn`

The `autograd` package is the cornerstone to all neural networks in `PyTorch`.
- `autograd` provides automatic differentiation fot all operations on all tensors. MEMORY
- Backpropagation is defined by how your code is excuted.
- Every iteration can be different.

## Tensor
---
__`torch.tensor`__ is the fundamental building block in PyTorch.
> If `requires_grad=True`, the tensor begins to "remember" all operations on it.
>
> When you call `.backward()` on a `torch.tensor` object that has the attribute `requires_grad=True`, all gradients are computed automatically.
    > - The gradient is stored in the `.grad` attribute.

To remove a tensor's "memory" use `.detach()` to detach it from the computational history. Detach it from its "experience". The tensor will also not be able to "remember" any future computations performed on it.

To prevent a torch from having memory, wrap the code block with:
> `with torch.no_grad():`

Note: Useful when evaluating a model because the model may have "trainable parameters" with `requires_grad=True` and we __don't need the gradients__.

`Function`

In [103]:
x = torch.tensor([1, 2, 3], dtype=float, requires_grad=True)
y = torch.tensor([1, 2, 3], dtype=float, requires_grad=True)
z = x + y

In [104]:
print(x)
print(y)

tensor([1., 2., 3.], dtype=torch.float64, requires_grad=True)
tensor([1., 2., 3.], dtype=torch.float64, requires_grad=True)


In [105]:
# Notice that when we create a new tensor by adding two tensors that have `requires_grad`=True,
# The new tensor `z` has memory of how it was created grad_fn=<AddBackward0>.
# It knows it was created by addition!
print(z)

tensor([2., 4., 6.], dtype=torch.float64, grad_fn=<AddBackward0>)


In [106]:
# Create a new tensor by mulitplying two existing tensors and a value/scaler
a = z * z * 10
a_scalar = a.mean()

In [107]:
# Reminder: Tensors can only contain float dtypes.

# Similarly, tensor `a` knows that it was created grad_fn=<MulBackward0> == multiplication!
print(a)

# We'll use a_scalar in the next section gradients
print(a_scalar)  # Interesting, this tensor remember the function used on it: grad_fn=<MeanBackward0>

tensor([ 40., 160., 360.], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor(186.6667, dtype=torch.float64, grad_fn=<MeanBackward0>)


In [108]:
b = torch.randn(2, 3)
b = ((b*10) / (b-1))

In [109]:
# Reminder: When you create new tensors, you must explicity set requires_grad=True

# This tensor does not have autograd enabled. Tensors created from b will not have autograd enabled.
print(f"Does tensor `b` have autograd enabled? {b.requires_grad}")

Does tensor `b` have autograd enabled? False


In [110]:
# Use .requires_grad_() function to add backpropagation to the tensor `b`
# Using .requires_grad_(True) modifies the tensor inplace, giving it memory.
b.requires_grad_(True)

tensor([[-2.3675,  5.2046,  3.6272],
        [ 5.6768,  3.4774,  6.8623]], requires_grad=True)

In [111]:
c = (a * b).sum()
print(a.grad_fn)  # created from: z * z * 10
print(b.grad_fn)  # A tensor created from scratch will not have memory. Only the ability to memorize.
print(c.grad_fn)  # created from: (a * b).sum()

None


## Gradients
---

In [112]:
# My first backpropagation!
a_scalar.backward()

Tensor `x` and tensor `y` are considered leaves, or leaf individually. These two tensors are the origin of `a_scalar`.
When backpropagation is executed, the gradient calculations stop at `x` and `y`.

`a_scaler` ----Backprop----> `a` ----Backprop----> `z` ----Backprop----> __`x` + `y`__

In [113]:
print(x.grad)
print(y.grad)

tensor([13.3333, 26.6667, 40.0000], dtype=torch.float64)
tensor([13.3333, 26.6667, 40.0000], dtype=torch.float64)


Interesting. Tensor `z` is called a __non-leaf__. Similar to decision tree leafs/pure leafs, this tensor is considered a node. 

```python
print(z.grad)
```

<div class='alert alert-block alert-danger'>UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
This is separate from the ipykernel package so we can avoid doing imports until </div>
  
### Example of vector-Jacobian product  
---

In [114]:
# Reminder x2: When creating a new tensor, you must explicitly set requires_grad=True
# To perform backprop and give the tensor memory.
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:  # x.data returns the values the tensor object with scalar values
    y *= 2
print(y)

tensor([ 877.5061, -408.6016, -641.1202], grad_fn=<MulBackward0>)


In [115]:
x.data.norm()

v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


### Stop autograd
---
- `with torch.no_grad():` code block
- `.requires_grad_(False)`
- `.detach()`

#### `with torch.no_grad():` code block
- Wrapping a tensor that was created with requires_grad=True will not be able to pass its __memory abilities__ to new tensors.

In [116]:
# Wrapping a tensor that has requires_grad=True inside a code block
# That removes the tensors memory as long as it's in the code block

# As we're learning, we know that tensors created from tensors that have requires_grad=True will
# pass their memory ability to the new tensor
print(f"Does tensor `x` have autograd enabled?")
print(x.requires_grad)
print("\nWhat about a new tensor? Would it have autograd enabled it was created from tensor `x`?")
print((x**2).requires_grad)


with torch.no_grad():
    print("\nDoes tensor `x` have auto_grad enabled now that it's in a torch.no_grad() code block?")
    print(x.requires_grad)
    print("\nWhat about the new tensor? Would it have auto grad enabled now that it's inside a torch.no_grad(): code block?")
    print((x**2).requires_grad)

Does tensor `x` have autograd enabled?
True

What about a new tensor? Would it have autograd enabled it was created from tensor `x`?
True

Does tensor `x` have auto_grad enabled now that it's in a torch.no_grad() code block?
True

What about the new tensor? Would it have auto grad enabled now that it's inside a torch.no_grad(): code block?
False


#### `.requires_grad_(False)`
- Most explicit way to remove a tensors' memory is by using `tensor_name.requires_grad_(False)`. 

In [117]:
print(f"Does tensor `x` have auto_grad enabled? {x.requires_grad}")
x.requires_grad_(False)
print()
print(f"What about now? {x.requires_grad}")

Does tensor `x` have auto_grad enabled? True

What about now? False


#### `.detach`
- Use `.detach()` to remove autograd but keep contents of tensor.

In [118]:
# Set tensor `x` with requires_grad=True to walkthrough using detach()
x.requires_grad_(True)

print(f"Does tensor `x` have auto_grad enabled? {x.requires_grad}")

# Create a new tensor from `x` that does not have requires_grad=True. Remove its memory.
y = x.detach()

print(f"Does tensor `y` have auto_grad enabled? {y.requires_grad}", end='\n\n')

# Although `y` does not have autograd enabled, both tensors contain the same values
print("Is tensor `x` equal to tensor `y`?")
print(x.eq(y).all())

# Another proof of equality
print(x==y)

Does tensor `x` have auto_grad enabled? True
Does tensor `y` have auto_grad enabled? False

Is tensor `x` equal to tensor `y`?
tensor(True)
tensor([True, True, True])


# Module 3 Neural Networks

Source of [tutorial](https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html).

Neural networks are created with the `torch.nn` package. Neural networks depend on autograd to define models and differentiate them!

`nn.Module` contains layers and method `forward()` (feed forward? Yes!) that returns the output.

Simple feed-forward networks takes an input, feeds it/pushes it through several layers, and returns an output.

Standard Operating Procedure to train neural networks:
1. Define the neural network with learnable parameters(or weights).
1. Interate over a dataset of inputs.
1. Process input through the network. Feed the data forward.
1. Compute the loss (how far is the output from being correct/how far off is the output from reality?)
1. Propagate gradients back into the networks parameters.
1. Update the weights of the NN, using an update rule: weight = weight * (learning_rate * gradient)

In [127]:
# Creating my first neural network! October 7th, 2020 2:59am
import torch
import torch.nn as nn
import torch.nn.functional as F

In [128]:
class Net(nn.Module):
    
    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 3x3 square convolution kernel?
        self.conv1 = nn.Conv2d(1, 6, 3)
        # 6 input image channels, 16 output channels, 3x3 square convolution kernel
        self.conv2 = nn.Conv2d(6, 16, 3)
        
        # Calculate weights for each layer
        self.fc1 = nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension?
        self.fc2 = nn.Linear(120, 84)  # I vaguely remember doing something like this in Deep Learning
        self.fc3 = nn.Linear(84, 10)
        
    def forward(self, x):
        # Feeding the inputs forward through the network
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size of the window is a square, you can only specify a single number.
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
         
    def num_flat_features(self, x):
        size = x.size()[1:]  # select all dimensions except for the batch dimension. 16?
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

In [129]:
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [130]:
# Learnable parameters of a model are returned using `net.parameters()`
params = list(net.parameters())
print(f"Number of parameters: {len(params)}")

# Each convolution is collapsed on the number of output channels.
for i in range(0, 10):
    print(params[i].size())

Number of parameters: 10
torch.Size([6, 1, 3, 3])
torch.Size([6])
torch.Size([16, 6, 3, 3])
torch.Size([16])
torch.Size([120, 576])
torch.Size([120])
torch.Size([84, 120])
torch.Size([84])
torch.Size([10, 84])
torch.Size([10])


This is interesting. Parameters 0 and 2 hold the weights of conv1 and conv2.
Layout of returned parameters at index 0 and 2

| Parameter | # Output Channels | # Input Image Channels | Row Length of Convolutional Kernel | Colum Length of Convolution Kernel |
|----|----|----|----|----|
|params[0]|6|1|3|3|
|params[2]|16|6|3|3|

In [131]:
input_tensor = torch.randn(1, 1, 32, 32)
out = net(input_tensor)
print(out)

tensor([[-0.0062,  0.0660,  0.0049, -0.0889, -0.0138, -0.0186,  0.0148,  0.1077,
         -0.0276,  0.0883]], grad_fn=<AddmmBackward>)


In [132]:
net.zero_grad()
out.backward(torch.rand(1, 10))

`torch.nn` only supports __mini-batches__.
Naturally, `torch.nn` only supports inputs that are a mini-batch of samples. No single samples. "All or none"

# Module 4 Train a Classifier