# Introduction to Pytorch
https://pytorch.org/tutorials/beginner/nlp/pytorch_tutorial.html

Notes:
- Deep learning uses __tensors__ to perform computations.

In [1]:
import torch
import numpy as np
import pandas as pd
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1);

## Creating Tensors
$\vec{v}$ to $\mathcal{T}$

https://en.wikiversity.org/wiki/Tensors/Definitions

https://pytorch.org/docs/stable/tensors.html

__Tensors__ can be constructed using:
1. List of lists
1. `pandas` series
1. `numpy` 1D-arrays
1. List of numbers in `Python`.

In [2]:
# My first lil' tensor :')
torch.tensor(1)

tensor(1)

Create a Tensor from a Python list

In [3]:
data = list(range(0, 10))

In [4]:
vector = torch.tensor(data)

Create a Tensor Matrix from:
1. List of lists
1. List of Series
1. `numpy` matrix
1. `pandas` matrix

In [5]:
# List of lists
lists = [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]

torch.tensor(lists)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
# List of Series
a = pd.Series(np.arange(0, 10))

torch.tensor((a, a, a))

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [7]:
# numpy matrix
matrix_A = np.random.uniform(1, 10, size=(3,3))

torch.tensor(matrix_A)

tensor([[3.3077, 5.7760, 5.3064],
        [4.3870, 7.5955, 5.5795],
        [5.1245, 2.7798, 7.5204]], dtype=torch.float64)

In [8]:
# pandas matrix
matrix_B = pd.DataFrame(
    np.random.randint(low=1,high=100,size=(10,10))
)

# torch.as_tensor(matrix_B) >>> TypeError: not a sequence
# torch.tensor(martix_B) >>> TypeError: not a sequence
torch.tensor(matrix_B.values)

tensor([[33, 50, 53,  8, 89, 16, 69, 15, 45, 31],
        [88, 20, 88, 84, 60,  2, 21, 80, 35, 95],
        [21, 48, 36, 27, 22, 17, 28, 25, 65, 28],
        [90, 47, 99, 77, 85, 48, 15, 45, 66, 75],
        [97, 99, 39, 36,  4, 64, 34, 70, 19, 75],
        [97, 11, 98,  2, 77, 34, 36,  8, 47, 63],
        [48,  7, 21, 10, 77, 21, 42, 98, 31, 17],
        [95,  2, 46, 82, 93, 77, 18,  4, 78, 35],
        [60, 64, 56, 53,  5,  7, 96, 18, 41, 26],
        [86, 25, 72, 44, 85, 71, 72, 21, 98, 58]])

Create a multi-dimensional Tensor from:

1. List of lists
2. List of Series
3. `numpy` matrix
4. `pandas` matrix

In [9]:
# List of lists
multi_lists = [[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]]]

Tensor = torch.tensor(multi_lists)
Tensor.shape

torch.Size([3, 3, 3])

In [10]:
# List of Series

In [11]:
# numpy matrix/ndarray

In [12]:
# pandas matrix

# Tensor Indexing

What is a multi-dimesional (n-D) tensor?

1. A multi-dimesional tensor has matrix indicies
2. A matrix has vector indicies
3. A vector has scalar indicies


## Indexing into a Vector
Let's look at this visually, starting with the vector we created, $\vec{v}$ `vector`.

In [13]:
print(vector.shape)
print(vector)

torch.Size([10])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### Vectors, Elements, and Scalars
$\vec{v}$ = \[0, 1, 2, 3, 4, 5, 6, 7, 8, 9\]

$\vec{v}$ has a shape of _m_ x _n_ = 10 rows, 1 column

__Plain English__:

- We have an array with 10 numbers
- The shape of the array is 10 rows x 1 column

__Explanation__:

- We're working with a vector with 10 elements.
- The elements are _scalars_ with values 0 - 9.

> __Elements__ in _linear algebra_ are also called entries, coefficients, or components.
>
> * Elements of a vector
> * Entries of a vector
> * Coefficients of a vector
> * Components of a vector
>
> They all mean the same thing!

> To explain this difference between _elements_ and _scalars_, let's imagine you're sitting down to a nice breakfast with your family. 

>There's pancakes, sausage, toast, yogurt, fruit, bacon, tea, coffee, orange juice, and water. Like a vulture, you circle each platter for the perfect piece and add it to your plate. Once you're finished you take a seat.

> 1. Your _plate is the vector_. It holds your delicious breakfast.
2. Each piece of fresh food you have on your plate is the _number of elements in your vector_.
3. The __name__ of each piece(s) (e.g. 3 strips of bacon, 2 pieces of fruit, 1 dallop of yogurt, 4 pancakes) are your _scalars_!

>Food for thought: You have a preference, the pieces on your plate are the direct result of weighted decisions _you make_.

> ### Let's setup our vector
> How many _elements_ do we have?
>-  3 (bacon strips)
>- \+ 2 (pieces of fruit)
>- \+ 1 (dallop of yogurt)
>- \+ 4 (pancakes) 
>- = 10 (pieces of food)
 
>Let's weight each food item:
>- Bacon - 6
>- Fruit - 9
>- Yogurt - 10
>- Pancakes - 11

>Let's make our plate:
>
>$\vec{plate}$ = \[6(bacon strip),
6(bacon strip),
6(bacon strip), 9(fruit), 9(fruit), 10(yogurt), 11(pancake), 11(pancake), 11(pancake), 11(pancake)\]

>Awesome. Let's not forget about our computer's breakfast, I mean _vector_:
>
>$\vec{v}$ = \[6, 6, 6, 9, 9, 10, 11, 11, 11, 11\]

> Help your family with the dishes :)

In [14]:
# Indexing into a vector results in a single value, our scalar.
# n is the number of elements in a vector, in our case 10
# ith element in vector is equal to v[i] here i=[1-1],....,i=[n-1]
# Here we get a scalar.
print(vector[0])
print(type(vector[0]))

tensor(0)
<class 'torch.Tensor'>


In [15]:
# To get a value, we need to pull the scalar out of the vector.
print(vector[0].item())
type(vector[0].item())

0


int

### Matrices and Vectors

Let's see what our matrix looks like

In [16]:
print(type(matrix_A))
print(matrix_A.ndim, 'dimensions')
print(matrix_A.shape)
print(matrix_A)

<class 'numpy.ndarray'>
2 dimensions
(3, 3)
[[3.30769998 5.77604548 5.30635634]
 [4.3869716  7.59554647 5.57953718]
 [5.12452874 2.77976516 7.52037903]]


## Indexing into the Matrix
- Whether you index into a matrix by row or column, you will get a vector.
> The size of the vector that is returned depends on the shape of the matrix. If a matrix has a shape of (4, 3)
> - Indexing by __row__ yields a vector of size 4.
> - Indexing by __column__ returns a vector of size 3.

In [17]:
# Indexing into our matrix using, well, index/bracket notation :D
# The bracket notation returns only column values in the first row
# print(matrix_A[0]) 
print(matrix_A[0,:])  # used explicit index notation
print(matrix_A[0].shape)

[3.30769998 5.77604548 5.30635634]
(3,)


In [18]:
# The bracket notation returns all rows, of the second column.
print(matrix_A[:,1].shape)
print(matrix_A[:,1])

(3,)
[5.77604548 7.59554647 2.77976516]


## Indexing into a Tensor

In [19]:
# Print out our Tensor
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [20]:
print(Tensor.ndim)
print(Tensor.shape)

3
torch.Size([3, 3, 3])


In [21]:
# Indexing into a Tensor return the first Matrix at index 0!
Tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Notes

* Tensors can be created from other numerical datatypes.
    * Similar to numpy and pandas, you can specify the datatype when you create a ndarray or dataframe/series.
* Most common datatypes used in Tensors are `float` and `long`.


# Creating Random Tensors

In [22]:
tensor_A = torch.randn(3, 3)

In [23]:
matrix_C = np.random.randn(3, 3)

In [24]:
tensor_A * matrix_C

tensor([[-0.1968,  0.0980, -0.1498],
        [ 0.7367,  0.4604, -0.1053],
        [ 1.4843,  0.1995,  0.3717]], dtype=torch.float64)

# Tensor Operations
https://pytorch.org/docs/stable/torch.html

In [28]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([5., 6., 7.])
z = x + y
print(z)

tensor([ 6.,  8., 10.])


In [34]:
torch.get_default_dtype()

torch.float32

In [35]:
z.numel()

3

In [55]:
torch.from_numpy(np.linspace(1, 10, 20))

tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000], dtype=torch.float64)

In [58]:
torch.linspace(1, 10, 20)

tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])

In [57]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Tensor Concatenation

Cannot concat `torch` dtypes with `numpy` dtypes.
``` python
torch.cat([tensor_A, matrix_C], 1)
#TypeError: expected Tensor as element 1 in argument 0, but got numpy.ndarray
```

In [40]:
# Using torch.as_tensor() to tansform numpy array to a tensor.
tensor_C = torch.as_tensor(matrix_C)

In [43]:
# Like pd.concat(), you can specify the axis you want to join the
# tensors on.
print("Column Tensor Join")
torch.cat([tensor_A, tensor_C], axis=1)

Column Tensor Join


tensor([[ 0.6614,  0.2669,  0.0617, -0.2975,  0.3670, -2.4284],
        [ 0.6213, -0.4519, -0.1661,  1.1858, -1.0188,  0.6341],
        [-1.5228,  0.3817, -1.0276, -0.9747,  0.5227, -0.3617]],
       dtype=torch.float64)

In [44]:
print("Row Tensor Join")
torch.cat([tensor_A, tensor_C], axis=0)

Row Tensor Join


tensor([[ 0.6614,  0.2669,  0.0617],
        [ 0.6213, -0.4519, -0.1661],
        [-1.5228,  0.3817, -1.0276],
        [-0.2975,  0.3670, -2.4284],
        [ 1.1858, -1.0188,  0.6341],
        [-0.9747,  0.5227, -0.3617]], dtype=torch.float64)

# Reshaping Tensors

In [64]:
# There are 24 elements in this tensor
tensor_x = torch.randn(2, 3, 4)

# .view() is equivalent of pd.reshape().
# Using .view() on a tensor to remove a dimension
tensor_x_view = tensor_x.view(2, 12)

print('Original Tensor N-Dimensions:', tensor_x.ndim)
print('Reshaped Tensor N-Dimensions:', tensor_x_view.ndim)

Original Tensor N-Dimensions: 3
Reshaped Tensor N-Dimensions: 2


In [67]:
# -1 in view will cause torch to infer the dimension.
tensor_x_view2 = tensor_x.view(2, -1)
print("Another way to reshape a tensor:", tensor_x_view2.shape)

Another way to reshape a tensor: torch.Size([2, 12])


# Computation Graphs and Automatic Differentiation

Computation graphs are essential to efficient deep learning programming.
- The programmer doesn't need to write the backpropagation
Computation graphs shows how your tensors are/were combined to give you the output.
- Specifies what parameters were involved in creating a tensor.
- Computation graphs can be used to calculate derivatives.
> `requires_grad` must be set to `True` in order to calculate derivatives and perform backpropagation.
>
>"...All this output tensor knows is its data and shape. It has no idea that it was the sum of two other tensors (it could have been read in from a file, it could be the result of some other operation, etc.)
>
>If `requires_grad`=`True`, the Tensor object keeps track of how it was created. Lets see it in action."

In [87]:
x = torch.tensor([6., 9., 4., 3., 8.], requires_grad=True)
y = torch.tensor([7., 3., 25., 84., 12.], requires_grad=True)
z = x + y
print(z)
print(z.grad_fn)

tensor([13., 12., 29., 87., 20.], grad_fn=<AddBackward0>)


In [88]:
s = z.sum()
print(s)
print(s.grad_fn)

tensor(161., grad_fn=<SumBackward0>)


In [89]:
# "...note if you run this block multiple times, the gradient will
# increment. That is because Pytorch accumulates the gradient into
# the .grad property, since for many models this is very convenient."
s.backward()
print(x.grad)

tensor([1., 1., 1., 1., 1.])


# The Cornerstone Fundamentals
##### \*\*\*Crucial for being a successful programmer in deep learning***
Tensors "know" how they were created when `requires_grad` = `True`

### Tensors without Backpropagation: `requires_grad=False`

In [121]:
a = torch.randn(4, 4)
b = torch.randn(4, 4)
c = a + b

In [122]:
print(f"Does Tensor `a` have grad? {a.requires_grad}")
print(f"Does Tensor `b` have grad? {b.requires_grad}")
print(f"Does Tensor `c` have grad? {c.requires_grad}")

Does Tensor `a` have grad? False
Does Tensor `b` have grad? False
Does Tensor `c` have grad? False


If a tensor is created without setting `requires_grad` = True, tensors created from "grad-less" tensors will be unable to perform derivatives. No derivatives, no backpropagation.

### Tensors _with_ Backpropagation: `requires_grad=True`

In [139]:
# Method `requires_grad_() sets requires_grad = True, inplace.
a.requires_grad_()
b.requires_grad_()

tensor([[-0.9965,  0.8073,  1.1739, -0.9398],
        [ 0.3861,  1.0473, -0.7327, -0.9168],
        [ 0.6867,  0.4209, -1.0214,  0.9886],
        [ 0.7806, -2.2049, -1.4975, -0.9023]], requires_grad=True)

In [140]:
# Seperate cells to show `requires_grad_()` changes the Tensors
# inplace.
a

tensor([[-0.7821, -1.4237,  1.6091, -0.0328],
        [-0.4327, -0.1150,  1.7964, -0.4774],
        [-2.7188, -0.2219,  0.3421,  1.1093],
        [-0.5276,  0.0849,  0.1945, -0.9418]], requires_grad=True)

In [141]:
b

tensor([[-0.9965,  0.8073,  1.1739, -0.9398],
        [ 0.3861,  1.0473, -0.7327, -0.9168],
        [ 0.6867,  0.4209, -1.0214,  0.9886],
        [ 0.7806, -2.2049, -1.4975, -0.9023]], requires_grad=True)

In [142]:
c = a + b
print(c.grad_fn)  # Our Tensors know how they were created!
print(c.requires_grad)

True


### Removing autograd from Tensors

In [143]:
# Using tensor.detach(), we can remove the values/scalars from
# a tensor without its 'memory' (ability to tell how it was created)
new_c = c.detach()

In [144]:
# new_c is not as cool as old 'c', it cannot perform backpropagation.

# "In essence, we have broken the Tensor away from its past history"


print(new_c.requires_grad)
print(new_c.grad_fn)

False
None


In [147]:
# wrap the code block tensor
with torch.no_grad():
    print((x * 42).requires_grad)

False


A tensor that is not operated on, changed, transformed inside the body of the `with` statement will be __unchanged__ if `requires_grad=True`.
``` python
with torch.no_grad():
    print(x.requires_grad)
```
\>\>\> __True__

# Tests

In [27]:
# torch.tensor?

In [23]:
a = pd.Series(np.arange(0, 10))

# torch.tensor((a, b, c).as_matrix())
# torch.cat((a, b, c))

torch.tensor(a)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

``` python
np.ndarray(vector) # tensors do not support indexing error.
np.array(vector)
pd.Series(vector)
pd.DataFrame(vector)
```

In [24]:
T = torch.arange(0, 10_000_000).reshape(1000, 100, 100)
M = np.arange(0, 10_000_000).reshape(1000, 100, 100)

In [25]:
%%timeit -r 10 -n 1_000
1 + T

16.2 ms ± 491 µs per loop (mean ± std. dev. of 10 runs, 1000 loops each)


In [26]:
%%timeit -r 10 -n 1_000
1 + M

16.5 ms ± 282 µs per loop (mean ± std. dev. of 10 runs, 1000 loops each)
