https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py
# Module 1: _What_ is PyTorch?
<br></br>
<dl>
    <dt>PyTorch</dt>
    <dd>is a Python-based computing package</dd>
</dl>

- A programming language that uses the power of GPU's to speed up calculations.
> I don't have an <font color=green>NVIDIA GPU</font> at the moment but I'll press on.
>
> I'll rent one here -> [NVIDIA GPU in the clouds above](https://cloud.google.com/)
- It's flexible and F.A.S.T.
    > `Python` + "...dang it's so fast it lit a <font color=red>_Torch_</font>" == __`PyTorch`__


## Getting Started
### Tensors

As I discovered in the first tutorial, `PyTorch` is similar to` NumPy`. Again, `PyTorch` uses __GPU's__, which makes it faster than `NumPy` for deep learning.

In [39]:
from __future__ import print_function
import torch
import numpy as np

> "An __uninitialized matrix__ is declared, but _does not_ contain __definite known values__ before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values."

### Creating an empty Tensor

In [16]:
# Creating an 'uninitialized matrix' with `tensor.empty()`
# So does it not have values?
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [15]:
# Interesting, the "values" (0's) that were placed in the empty tensor matrix
# changed to actual values once operated on...
x + 1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

### Creating a Random Martrix

In [20]:
# torch.randn?

In [32]:
x = torch.randn(5, 7, dtype=torch.float64)
print(x)

tensor([[-1.3603,  0.9628,  0.4029,  1.1300,  1.4998,  1.5566,  0.8811],
        [ 0.3264, -1.0985, -0.7154, -1.2161, -0.8663,  0.0604,  0.6977],
        [-0.5846,  0.1354,  0.9601, -0.2476, -1.5285, -1.4529, -0.8555],
        [-2.1218, -1.4385,  1.4823, -0.1558, -1.0033,  0.6939,  0.4681],
        [-0.6294, -0.4614,  1.5029,  0.6653, -0.7603, -1.0208,  0.2344]],
       dtype=torch.float64)


### Creating a Matrix of Zeros and Ones

https://pytorch.org/docs/stable/tensors.html

In [25]:
torch.zeros(5, 5, dtype=torch.long)  # 64-bit integer (signed)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [27]:
torch.zeros(5, 5, dtype=torch.bool)

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

In [36]:
torch.ones(5, 5, dtype=torch.float64)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

In [33]:
torch.ones(5, 5, dtype=torch.bool)

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [38]:
torch.ones(3, 3, dtype=torch.cdouble)

tensor([[1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j]], dtype=torch.complex128)

#### Notes
PyTorch tensors are unable to infer True as 1 and False as 0's
``` python
torch.ones(5, 5, dtype=torch.bool).mean()
```
<font color=red>RuntimeError</font>: Can only calculate the mean of floating types. Got Bool instead.


# Create a Tensor from Data

In [61]:
# Create a Tensor using NumPy to generate data
x = torch.tensor(np.random.randint(1, 11, size=(10, 10)))

# Create a Tensor using PyTorch built in method `.randint()`
y = torch.randint(1, 11, size=(10, 10))

In [59]:
print(x.dtype)
print(x)

torch.int64
tensor([[10,  5,  8,  6, 10,  8,  1,  4,  8,  4],
        [ 9,  5,  1,  7,  3,  8,  9,  8,  7,  6],
        [ 1,  6,  5,  5,  5,  3,  5,  6,  7,  1],
        [ 5,  7,  9,  5,  7,  4,  2,  5,  3, 10],
        [10,  9,  8,  9,  2,  1, 10,  3,  5,  9],
        [ 6,  3,  9, 10,  1,  2,  4,  1,  7,  2],
        [ 8,  5,  6,  2,  5,  3,  2,  3,  3,  1],
        [10,  3,  7,  9,  7,  5, 10,  6, 10,  1],
        [10,  3,  2,  3,  5,  7, 10,  6,  9,  4],
        [ 5,  1,  3,  3,  1,  9,  2,  5,  2,  7]])


In [60]:
print(y.dtype)
y

torch.int64


tensor([[ 8,  3,  3,  4,  4,  3,  9,  1,  1,  8],
        [ 6,  1,  3,  7,  9,  8,  6,  4,  5,  1],
        [ 8,  7, 10,  8,  9,  1,  3,  9,  6,  1],
        [ 9,  7,  3,  4,  5,  4,  8,  6, 10,  8],
        [ 8,  7,  5,  5,  8,  6,  3,  8,  6,  8],
        [ 8,  1,  1,  7,  6,  3,  3,  9,  5,  7],
        [ 3,  1,  1, 10,  2, 10,  2,  1,  5,  2],
        [ 2,  1,  7,  1,  5,  8,  4,  6,  3, 10],
        [ 2, 10,  4, 10,  2, 10, 10,  3,  2,  4],
        [ 1,  1,  2,  9,  9,  8,  3,  6,  6, 10]])

### Create a Tensor based on an existing Tensor
#### Creating Tensors with new dimensions, dtypes, and requires_grad

In [62]:
# Using .new_*() methods, we can create new Tensors!
# If needed, we can also change the dtype

new_x1 = x.new_ones(3, 3)
new_x2 = x.new_ones(5, 5, dtype=torch.double)

In [63]:
print(new_x1.dtype)
new_x1

torch.int64


tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [64]:
print(new_x2.dtype)
new_x2

torch.float64


tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

The newly created Tensors do not have `requires_grad=True` because:
1. The original Tensor it was created from did not have `requires_grad=True`
2. When creating the Tensor from an exisiting Tensor, __WE__ did not specifiy `requires_grad=True`.

>__REMINDER__! `requires_grad=True` can only be set on Tensors of `dtype=float`!
> Example:
> ``` python
> # new_x1.dtype >>> torch.int64
new_x1.requires_grad_()
> ```
> If you try to set `requires_grad=True` on a Tensor of dtype `torch.int64` you'll get the following error.
>
> <font color=red>RuntimeError</font>: only Tensors of _floating point dtype_ can require gradients.

In [69]:
print(new_x1.requires_grad)
print(new_x2.requires_grad)

False
False


In [71]:
# print(new_x1.requires_grad_())

# Now our new tensor has memory.
print(new_x2.requires_grad_())

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64, requires_grad=True)


#### Creating Tensors with the SAME dimensions, different dtypes, requires_grad

# Module 2 Differentation through Autograd

# Module 3 Training a Neural Network by Defining a Neural Network

# Module 4 Train a Classifier