# Introduction to Pytorch
https://pytorch.org/tutorials/beginner/nlp/pytorch_tutorial.html

Notes:
- Deep learning uses __tensors__ to perform computations.

In [1]:
import torch
import numpy as np
import pandas as pd
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1);

## Creating Tensors
$\vec{v}$ to $\mathcal{T}$

https://en.wikiversity.org/wiki/Tensors/Definitions

https://pytorch.org/docs/stable/tensors.html

__Tensors__ can be constructed using:
1. List of lists
1. `pandas` series
1. `numpy` 1D-arrays
1. List of numbers in `Python`.

In [2]:
# My first lil' tensor :')
torch.tensor(1)

tensor(1)

Create a Tensor from a Python list

In [3]:
data = list(range(0, 10))

In [4]:
vector = torch.tensor(data)

Create a Tensor Matrix from:
1. List of lists
1. List of Series
1. `numpy` matrix
1. `pandas` matrix

In [5]:
# List of lists
lists = [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]

torch.tensor(lists)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
# List of Series
a = pd.Series(np.arange(0, 10))

torch.tensor((a, a, a))

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=torch.int32)

In [7]:
# numpy matrix
matrix_A = np.random.uniform(1, 10, size=(3,3))

torch.tensor(matrix_A)

tensor([[9.9565, 5.3255, 9.6886],
        [8.1861, 8.4726, 5.9775],
        [2.4068, 1.3501, 4.7444]], dtype=torch.float64)

In [8]:
# pandas matrix
matrix_B = pd.DataFrame(
    np.random.randint(low=1,high=100,size=(10,10))
)

# torch.as_tensor(matrix_B) >>> TypeError: not a sequence
# torch.tensor(martix_B) >>> TypeError: not a sequence
torch.tensor(matrix_B.values)

tensor([[76, 73, 32, 87, 32, 19, 88, 63, 66, 54],
        [82, 61,  3,  2, 81, 96, 22, 33, 18, 72],
        [54, 98, 14, 74, 16, 92,  8, 41, 31, 39],
        [35, 16, 56, 50, 29, 36,  7, 49, 53, 19],
        [11, 93, 86, 83, 39, 89, 58, 69,  6, 83],
        [87, 36, 33, 52, 69, 27, 39, 39, 53, 47],
        [10, 46, 27, 44, 42, 53, 44, 79, 17, 99],
        [64, 33,  4, 97, 91, 25, 48, 27, 78, 58],
        [52, 12, 83, 74, 89, 70,  7, 86, 90, 61],
        [71, 71, 37, 89, 12, 22,  9, 95, 23, 82]], dtype=torch.int32)

Create a multi-dimensional Tensor from:

1. List of lists
2. List of Series
3. `numpy` matrix
4. `pandas` matrix

In [9]:
# List of lists
multi_lists = [[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]]]

Tensor = torch.tensor(multi_lists)
Tensor.shape

torch.Size([3, 3, 3])

In [10]:
# List of Series
a = pd.Series(np.arange(1, 10))
b = pd.Series(np.arange(1, 10))
c = pd.Series(np.arange(1, 10))
d = pd.Series(np.arange(1, 10))

In [11]:
torch.tensor([a, b, c, d],
             dtype=torch.float64,
             requires_grad=True)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]], dtype=torch.float64,
       requires_grad=True)

In [12]:
# numpy matrix/ndarray
e = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

In [13]:
torch.tensor(e, dtype=torch.float64, requires_grad=True)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]], dtype=torch.float64, requires_grad=True)

In [14]:
np.arange(16).reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

```python
# pandas matrix
torch.tensor(pd.DataFrame(np.arange(16).reshape(4, 4)),
             dtype=torch.float64,
             requires_grad=True)

# Pandas DataFrames cannot be used to create tensor object.
# You must extract the values from the dataframe using `.values()`


---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-75-22b40f39bc99> in <module>
      1 # pandas matrix
----> 2 torch.tensor(pd.DataFrame(np.arange(16).reshape(4, 4)),
      3              dtype=torch.float64,
      4              requires_grad=True)

TypeError: not a sequence
```

# Tensor Indexing

What is a multi-dimesional (n-D) tensor?

1. A multi-dimesional tensor has matrix indicies
2. A matrix has vector indicies
3. A vector has scalar indicies


## Indexing into a Vector
Let's look at this visually, starting with the vector we created, $\vec{v}$ `vector`.

In [15]:
print(vector.shape)
print(vector)

torch.Size([10])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### Vectors, Elements, and Scalars
$\vec{v}$ = \[0, 1, 2, 3, 4, 5, 6, 7, 8, 9\]

$\vec{v}$ has a shape of _m_ x _n_ = 10 rows, 1 column

__Plain English__:

- We have an array with 10 numbers
- The shape of the array is 10 rows x 1 column

__Explanation__:

- We're working with a vector with 10 elements.
- The elements are _scalars_ with values 0 - 9.

> __Elements__ in _linear algebra_ are also called entries, coefficients, or components.
>
> * Elements of a vector
> * Entries of a vector
> * Coefficients of a vector
> * Components of a vector
>
> They all mean the same thing!

> To explain this difference between _elements_ and _scalars_, let's imagine you're sitting down to a nice breakfast with your family. 

>There's pancakes, sausage, toast, yogurt, fruit, bacon, tea, coffee, orange juice, and water. Like a vulture, you circle each platter for the perfect piece and add it to your plate. Once you're finished you take a seat.

> 1. Your _plate is the vector_. It holds your delicious breakfast.
2. Each piece of fresh food you have on your plate is the _number of elements in your vector_.
3. The __name__ of each piece(s) (e.g. 3 strips of bacon, 2 pieces of fruit, 1 dallop of yogurt, 4 pancakes) are your _scalars_!

>Food for thought: You have a preference, the pieces on your plate are the direct result of weighted decisions _you make_.

> ### Let's setup our vector
> How many _elements_ do we have?
>-  3 (bacon strips)
>- \+ 2 (pieces of fruit)
>- \+ 1 (dallop of yogurt)
>- \+ 4 (pancakes) 
>- = 10 (pieces of food)
 
>Let's weight each food item:
>- Bacon - 5
>- Fruit - 9
>- Yogurt - 10
>- Pancakes - 11

>Let's make our plate:
>
>$\vec{plate}$ = \[6(bacon strip),
6(bacon strip),
6(bacon strip), 9(fruit), 9(fruit), 10(yogurt), 11(pancake), 11(pancake), 11(pancake), 11(pancake)\]

>Awesome. Let's not forget about our computer's breakfast, I mean _vector_:
>
>$\vec{v}$ = \[5, 5, 5, 9, 9, 10, 11, 11, 11, 11\]

> Help your family with the dishes :)

In [16]:
# Indexing into a vector results in a single value, our scalar.
# n is the number of elements in a vector, in our case 10
# ith element in vector is equal to v[i] here i=[1-1],....,i=[n-1]
# Here we get a scalar.
print(vector[0])
print(type(vector[0]))

tensor(0)
<class 'torch.Tensor'>


In [17]:
# To get a value, we need to pull the scalar out of the vector.
print(vector[0].item())
type(vector[0].item())

0


int

### Matrices and Vectors

Let's see what our matrix looks like

In [18]:
print(type(matrix_A))
print(matrix_A.ndim, 'dimensions')
print(matrix_A.shape)
print(matrix_A)

<class 'numpy.ndarray'>
2 dimensions
(3, 3)
[[9.95652199 5.32553101 9.68859943]
 [8.18606239 8.47262493 5.97747344]
 [2.4068148  1.35010209 4.74439807]]


## Indexing into the Matrix
- Whether you index into a matrix by row or column, you will get a vector.
> The size of the vector that is returned depends on the shape of the matrix. If a matrix has a shape of (4, 3)
> - Indexing by __row__ yields a vector of size 4.
> - Indexing by __column__ returns a vector of size 3.

In [19]:
# Indexing into our matrix using, well, index/bracket notation :D
# The bracket notation returns only column values in the first row
# print(matrix_A[0]) 
print(matrix_A[0,:])  # used explicit index notation
print(matrix_A[0].shape)

[9.95652199 5.32553101 9.68859943]
(3,)


In [20]:
# The bracket notation returns all rows, of the second column.
print(matrix_A[:,1].shape)
print(matrix_A[:,1])

(3,)
[5.32553101 8.47262493 1.35010209]


## Indexing into a Tensor

In [21]:
# Print out our Tensor
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [22]:
print(Tensor.ndim)
print(Tensor.shape)

3
torch.Size([3, 3, 3])


In [23]:
# Indexing into a Tensor return the first Matrix at index 0!
Tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Notes

* Tensors can be created from other numerical datatypes.
    * Similar to numpy and pandas, you can specify the datatype when you create a ndarray or dataframe/series.
* Most common datatypes used in Tensors are `float` and `long`.


# Creating Random Tensors

In [24]:
tensor_A = torch.randn(3, 3)

In [25]:
matrix_C = np.random.randn(3, 3)

In [26]:
tensor_A * matrix_C

tensor([[-0.5005, -0.1047,  0.1011],
        [ 0.4217,  0.2843, -0.1316],
        [-0.5932,  0.5813,  1.3796]], dtype=torch.float64)

# Tensor Operations
https://pytorch.org/docs/stable/torch.html

In [27]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([5., 6., 7.])
z = x + y
print(z)

tensor([ 6.,  8., 10.])


In [28]:
torch.get_default_dtype()

torch.float32

In [29]:
z.numel()

3

In [30]:
torch.from_numpy(np.linspace(1, 10, 20))

tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000], dtype=torch.float64)

In [31]:
torch.linspace(1, 10, 20)

tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])

In [32]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Tensor Concatenation

Cannot concat `torch` dtypes with `numpy` dtypes.
``` python
torch.cat([tensor_A, matrix_C], 1)
#TypeError: expected Tensor as element 1 in argument 0, but got numpy.ndarray
```

In [33]:
# Using torch.as_tensor() to tansform numpy array to a tensor.
tensor_C = torch.as_tensor(matrix_C)

In [34]:
# Like pd.concat(), you can specify the axis you want to join the
# tensors on.
print("Column Tensor Join")
torch.cat([tensor_A, tensor_C], axis=1)

Column Tensor Join


tensor([[ 0.6614,  0.2669,  0.0617, -0.7568, -0.3922,  1.6395],
        [ 0.6213, -0.4519, -0.1661,  0.6787, -0.6292,  0.7920],
        [-1.5228,  0.3817, -1.0276,  0.3895,  1.5229, -1.3426]],
       dtype=torch.float64)

In [35]:
print("Row Tensor Join")
torch.cat([tensor_A, tensor_C], axis=0)

Row Tensor Join


tensor([[ 0.6614,  0.2669,  0.0617],
        [ 0.6213, -0.4519, -0.1661],
        [-1.5228,  0.3817, -1.0276],
        [-0.7568, -0.3922,  1.6395],
        [ 0.6787, -0.6292,  0.7920],
        [ 0.3895,  1.5229, -1.3426]], dtype=torch.float64)

# Reshaping Tensors

In [36]:
# There are 24 elements in this tensor
tensor_x = torch.randn(2, 3, 4)

# .view() is equivalent of pd.reshape().
# Using .view() on a tensor to remove a dimension
tensor_x_view = tensor_x.view(2, 12)

print('Original Tensor N-Dimensions:', tensor_x.ndim)
print('Reshaped Tensor N-Dimensions:', tensor_x_view.ndim)

Original Tensor N-Dimensions: 3
Reshaped Tensor N-Dimensions: 2


In [37]:
# -1 in view will cause torch to infer the dimension.
tensor_x_view2 = tensor_x.view(2, -1)
print("Another way to reshape a tensor:", tensor_x_view2.shape)

Another way to reshape a tensor: torch.Size([2, 12])


# Computation Graphs and Automatic Differentiation

Computation graphs are essential to efficient deep learning programming.
- The programmer doesn't need to write the backpropagation
Computation graphs shows how your tensors are/were combined to give you the output.
- Specifies what parameters were involved in creating a tensor.
- Computation graphs can be used to calculate derivatives.
> `requires_grad` must be set to `True` in order to calculate derivatives and perform backpropagation.
>
>"...All this output tensor knows is its data and shape. It has no idea that it was the sum of two other tensors (it could have been read in from a file, it could be the result of some other operation, etc.)
>
>If `requires_grad`=`True`, the Tensor object keeps track of how it was created. Lets see it in action."

In [38]:
x = torch.tensor([6., 9., 4., 3., 8.], requires_grad=True)
y = torch.tensor([7., 3., 25., 84., 12.], requires_grad=True)
z = x + y
print(z)
print(z.grad_fn)

tensor([13., 12., 29., 87., 20.], grad_fn=<AddBackward0>)


In [39]:
s = z.sum()
print(s)
print(s.grad_fn)

tensor(161., grad_fn=<SumBackward0>)


In [40]:
# "...note if you run this block multiple times, the gradient will
# increment. That is because Pytorch accumulates the gradient into
# the .grad property, since for many models this is very convenient."
s.backward()
print(x.grad)

tensor([1., 1., 1., 1., 1.])


# The Cornerstone Fundamentals
##### \*\*\*Crucial for being a successful programmer in deep learning***
Tensors "know" how they were created when `requires_grad` = `True`

### Tensors without Backpropagation: `requires_grad=False`

In [41]:
a = torch.randn(4, 4)
b = torch.randn(4, 4)
c = a + b

In [42]:
print(f"Does Tensor `a` have grad? {a.requires_grad}")
print(f"Does Tensor `b` have grad? {b.requires_grad}")
print(f"Does Tensor `c` have grad? {c.requires_grad}")

Does Tensor `a` have grad? False
Does Tensor `b` have grad? False
Does Tensor `c` have grad? False


If a tensor is created without setting:
```python
requires_grad=True
```
Tensors created from "grad-less" tensors will inherit the inability to perform auto differentiation i.e. unable to perform derivatives. No derivatives, no backpropagation. No backprop no neural networks.

### Tensors _with_ Backpropagation: `requires_grad=True`

In [43]:
# Method `requires_grad_() sets requires_grad = True, inplace.
a.requires_grad_()
b.requires_grad_()

tensor([[ 0.4100,  0.4085,  0.2579,  1.0950],
        [-0.5065,  0.0998, -0.6540,  0.7317],
        [-1.4567,  1.6089,  0.0938, -1.2597],
        [ 0.2546, -0.5020, -1.0412,  0.7323]], requires_grad=True)

In [44]:
# Seperate cells to show `requires_grad_()` changes the Tensors
# inplace.
a

tensor([[ 0.4533,  1.1422,  0.2486, -1.7754],
        [-0.0255, -1.0233, -0.5962, -1.0055],
        [ 0.4285,  1.4761, -1.7869,  1.6103],
        [-0.7040, -0.1853, -0.9962, -0.8313]], requires_grad=True)

In [45]:
b

tensor([[ 0.4100,  0.4085,  0.2579,  1.0950],
        [-0.5065,  0.0998, -0.6540,  0.7317],
        [-1.4567,  1.6089,  0.0938, -1.2597],
        [ 0.2546, -0.5020, -1.0412,  0.7323]], requires_grad=True)

In [46]:
c = a + b
print(c.grad_fn)  # Our Tensors know how they were created!
print(c.requires_grad)

True


### Removing autograd from Tensors

In [47]:
# Using tensor.detach(), we can remove the values/scalars from
# a tensor without its 'memory' (ability to tell how it was created)
new_c = c.detach()

In [48]:
# new_c is not as cool as old 'c', it cannot perform backpropagation.

# "In essence, we have broken the Tensor away from its past history"


print(new_c.requires_grad)
print(new_c.grad_fn)

False
None


In [49]:
# wrap the code block tensor
with torch.no_grad():
    print((x * 42).requires_grad)

False


A tensor that is not operated on, changed, or transformed inside the body of the `with` statement will remain __unchanged__ i.e. will retain the ability to perform backprop if `requires_grad=True`. I think this situation may be rare.
``` python
with torch.no_grad():
    print(x.requires_grad)
```
\>\>\> __True__

In [57]:
# Code from the cell above.
with torch.no_grad():
    print(x.requires_grad)

True


# Tests

In [50]:
# torch.tensor?

In [51]:
a = pd.Series(np.arange(0, 10))

# torch.tensor((a, b, c).as_matrix())
# torch.cat((a, b, c))

torch.tensor(a)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

``` python
np.ndarray(vector) # tensors do not support indexing error.
np.array(vector)
pd.Series(vector)
pd.DataFrame(vector)
```

In [52]:
T = torch.arange(0, 10_000_000).reshape(1000, 100, 100)
M = np.arange(0, 10_000_000).reshape(1000, 100, 100)

In [53]:
# This was worth it! I am eternally grateful!
%%timeit -r 10 -n 1_000
1 + T

16.9 ms ± 1.4 ms per loop (mean ± std. dev. of 10 runs, 1000 loops each)


In [54]:
%%timeit -r 10 -n 1_000
1 + M

11.8 ms ± 483 µs per loop (mean ± std. dev. of 10 runs, 1000 loops each)
