# Introduction to Pytorch
https://pytorch.org/tutorials/beginner/nlp/pytorch_tutorial.html

Notes:
- Deep learning uses __tensors__ to perform computations.

In [25]:
import torch
import numpy as np
import pandas as pd
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1);

## Creating Tensors
$\vec{v}$ to $\mathcal{T}$

https://en.wikiversity.org/wiki/Tensors/Definitions

https://pytorch.org/docs/stable/tensors.html

__Tensors__ can be constructed using:
1. List of lists
1. `pandas` series
1. `numpy` 1D-arrays
1. List of numbers in `Python`.

In [26]:
# My first lil' tensor :')
torch.tensor(1)

tensor(1)

Create a Tensor from a Python list

In [27]:
data = list(range(0, 10))

In [28]:
vector = torch.tensor(data)

Create a Tensor Matrix from:
1. List of lists
1. List of Series
1. `numpy` matrix
1. `pandas` matrix

In [29]:
# List of lists
lists = [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]

torch.tensor(lists)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [30]:
# List of Series
a = pd.Series(np.arange(0, 10))

torch.tensor((a, a, a))

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [31]:
# numpy matrix
matrix_A = np.random.uniform(1, 10, size=(3,3))

torch.tensor(matrix_A)

tensor([[9.0824, 3.1404, 1.4336],
        [6.2108, 2.6634, 5.1209],
        [4.7748, 5.0115, 6.0705]], dtype=torch.float64)

In [32]:
# pandas matrix
matrix_B = pd.DataFrame(
    np.random.randint(low=1,high=100,size=(10,10))
)

# torch.as_tensor(matrix_B) >>> TypeError: not a sequence
# torch.tensor(martix_B) >>> TypeError: not a sequence
torch.tensor(matrix_B.values)

tensor([[11, 40, 44,  8, 94, 92, 15, 91, 37, 48],
        [58, 68, 12,  6, 48, 42, 24, 50, 82, 70],
        [91, 93, 62, 42, 85, 69, 94, 67, 57, 93],
        [68, 36, 68,  2,  9, 27, 42, 31, 83, 31],
        [79,  8, 12, 28, 14, 91, 40, 38, 14, 22],
        [90, 26, 88, 93, 21, 18, 14, 68, 61,  9],
        [86,  9, 82, 40, 62, 85, 40, 79, 28, 63],
        [52, 23, 84, 94, 76, 43,  3, 82, 26, 24],
        [68, 14, 97, 25, 49, 20, 26, 17, 44, 20],
        [ 8, 96, 40, 33, 80, 20,  6,  2, 38, 20]])

Create a multi-dimensional Tensor from:

1. List of lists
2. List of Series
3. `numpy` matrix
4. `pandas` matrix

In [33]:
# List of lists
multi_lists = [[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]]]

Tensor = torch.tensor(multi_lists)
Tensor.shape

torch.Size([3, 3, 3])

In [34]:
# List of Series

In [35]:
# numpy matrix/ndarray

In [36]:
# pandas matrix

# Tensor Indexing

What is a multi-dimesional (n-D) tensor?

1. A multi-dimesional tensor has matrix indicies
2. A matrix has vector indicies
3. A vector has scalar indicies


## Indexing into a Vector
Let's look at this visually, starting with the vector we created, $\vec{v}$ `vector`.

In [37]:
print(vector.shape)
print(vector)

torch.Size([10])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### Vectors, Elements, and Scalars
$\vec{v}$ = \[0, 1, 2, 3, 4, 5, 6, 7, 8, 9\]

$\vec{v}$ has a shape of _m_ x _n_ = 10 rows, 1 column

__Plain English__:

- We have an array with 10 numbers
- The shape of the array is 10 rows x 1 column

__Explanation__:

- We're working with a vector with 10 elements.
- The elements are _scalars_ with values 0 - 9.

> __Elements__ in _linear algebra_ are also called entries, coefficients, or components.
>
> * Elements of a vector
> * Entries of a vector
> * Coefficients of a vector
> * Components of a vector
>
> They all mean the same thing!

> To explain this difference between _elements_ and _scalars_, let's imagine you're sitting down to a nice breakfast with your family. 

>There's pancakes, sausage, toast, yogurt, fruit, bacon, tea, coffee, orange juice, and water. Like a vulture, you circle each platter for the perfect piece and add it to your plate. Once you're finished you take a seat.

> 1. Your _plate is the vector_. It holds your delicious breakfast.
2. Each piece of fresh food you have on your plate is the _number of elements in your vector_.
3. The __name__ of each piece(s) (e.g. 3 strips of bacon, 2 pieces of fruit, 1 dallop of yogurt, 4 pancakes) are your _scalars_!

>Food for thought: You have a preference, the pieces on your plate are the direct result of weighted decisions _you make_.

> ### Let's setup our vector
> How many _elements_ do we have?
>-  3 (bacon strips)
>- \+ 2 (pieces of fruit)
>- \+ 1 (dallop of yogurt)
>- \+ 4 (pancakes) 
>- = 10 (pieces of food)
 
>Let's weight each food item:
>- Bacon - 6
>- Fruit - 9
>- Yogurt - 10
>- Pancakes - 11

>Let's make our plate:
>
>$\vec{plate}$ = \[6(bacon strip),
6(bacon strip),
6(bacon strip), 9(fruit), 9(fruit), 10(yogurt), 11(pancake), 11(pancake), 11(pancake), 11(pancake)\]

>Awesome. Let's not forget about our computer's breakfast, I mean _vector_:
>
>$\vec{v}$ = \[6, 6, 6, 9, 9, 10, 11, 11, 11, 11\]

> Help your family with the dishes :)

In [38]:
# Indexing into a vector results in a single value, our scalar.
# n is the number of elements in a vector, in our case 10
# ith element in vector is equal to v[i] here i=[1-1],....,i=[n-1]
# Here we get a scalar.
print(vector[0])
print(type(vector[0]))

tensor(0)
<class 'torch.Tensor'>


In [39]:
# To get a value, we need to pull the scalar out of the vector.
print(vector[0].item())
type(vector[0].item())

0


int

### Matrices and Vectors

Let's see what our matrix looks like

In [40]:
print(type(matrix_A))
print(matrix_A.ndim, 'dimensions')
print(matrix_A.shape)
print(matrix_A)

<class 'numpy.ndarray'>
2 dimensions
(3, 3)
[[9.08243574 3.14041421 1.43362261]
 [6.2107605  2.66339374 5.12088437]
 [4.77475076 5.01145376 6.07047656]]


## Indexing into the Matrix
- Whether you index into a matrix by row or column, you will get a vector.
> The size of the vector that is returned depends on the shape of the matrix. If a matrix has a shape of (4, 3)
> - Indexing by __row__ yields a vector of size 4.
> - Indexing by __column__ returns a vector of size 3.

In [41]:
# Indexing into our matrix using, well, index/bracket notation :D
# The bracket notation returns only column values in the first row
# print(matrix_A[0]) 
print(matrix_A[0,:])  # used explicit index notation
print(matrix_A[0].shape)

[9.08243574 3.14041421 1.43362261]
(3,)


In [42]:
# The bracket notation returns all rows, of the second column.
print(matrix_A[:,1].shape)
print(matrix_A[:,1])

(3,)
[3.14041421 2.66339374 5.01145376]


## Indexing into a Tensor

In [43]:
# Print out our Tensor
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [44]:
print(Tensor.ndim)
print(Tensor.shape)

3
torch.Size([3, 3, 3])


In [45]:
# Indexing into a Tensor return the first Matrix at index 0!
Tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Notes

* Tensors can be created from other numerical datatypes.
    * Similar to numpy and pandas, you can specify the datatype when you create a ndarray or dataframe/series.
* Most common datatypes used in Tensors are `float` and `long`.


# Creating Random Tensors

In [56]:
tensor_A = torch.randn(3, 3)

In [57]:
matrix_C = np.random.randn(3, 3)

In [58]:
tensor_A * matrix_C

tensor([[-0.7228, -0.5294, -0.0600],
        [-0.9601, -0.4517,  0.0274],
        [-2.3543,  0.6199,  0.0153]], dtype=torch.float64)

# Tensor Concatenation

Cannot concat `torch` dtypes with `numpy` dtypes.
``` python
torch.cat([tensor_A, matrix_C], 1)
#TypeError: expected Tensor as element 1 in argument 0, but got numpy.ndarray
```

# Tests

In [27]:
# torch.tensor?

In [23]:
a = pd.Series(np.arange(0, 10))

# torch.tensor((a, b, c).as_matrix())
# torch.cat((a, b, c))

torch.tensor(a)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

``` python
np.ndarray(vector) # tensors do not support indexing error.
np.array(vector)
pd.Series(vector)
pd.DataFrame(vector)
```

In [24]:
T = torch.arange(0, 10_000_000).reshape(1000, 100, 100)
M = np.arange(0, 10_000_000).reshape(1000, 100, 100)

In [25]:
%%timeit -r 10 -n 1_000
1 + T

16.2 ms ± 491 µs per loop (mean ± std. dev. of 10 runs, 1000 loops each)


In [26]:
%%timeit -r 10 -n 1_000
1 + M

16.5 ms ± 282 µs per loop (mean ± std. dev. of 10 runs, 1000 loops each)
