# Introduction to Pytorch
https://pytorch.org/tutorials/beginner/nlp/pytorch_tutorial.html

Notes:
- Deep learning uses __tensors__ to perform computations.

In [13]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import pandas as pd

torch.manual_seed(1);

## Creating Tensors
$\vec{v}$ to $\mathcal{T}$

https://en.wikiversity.org/wiki/Tensors/Definitions

https://pytorch.org/docs/stable/tensors.html

__Tensors__ can be constructed using:
1. List of lists
1. `pandas` series
1. `numpy` 1D-arrays
1. List of numbers in `Python`.

In [14]:
# My first lil' tensor :')
torch.tensor(1)

tensor(1)

Create a Tensor from a Python list

In [15]:
data = list(range(0, 10))

In [16]:
vector = torch.tensor(data)

Create a Tensor Matrix from:
1. List of lists
1. List of Series
1. `numpy` matrix
1. `pandas` matrix

In [17]:
# List of lists
lists = [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]

torch.tensor(lists)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
# List of Series
a = pd.Series(np.arange(0, 10))

torch.tensor((a, a, a))

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [19]:
# numpy matrix
matrix_A = np.random.uniform(1, 10, size=(3,3))

torch.tensor(matrix_A)

tensor([[9.6162, 9.6506, 4.9820],
        [6.7036, 4.2751, 2.8464],
        [3.9134, 1.0935, 9.3289]], dtype=torch.float64)

In [20]:
# pandas matrix
matrix_B = pd.DataFrame(
    np.random.randint(low=1,high=100,size=(10,10))
)

# torch.as_tensor(matrix_B) >>> TypeError: not a sequence
# torch.tensor(martix_B) >>> TypeError: not a sequence
torch.tensor(matrix_B.values)

tensor([[54, 79, 79,  7, 19, 61, 38, 84, 57, 94],
        [44, 76, 69, 29, 49,  3, 22,  1, 72, 96],
        [44, 13, 27,  4, 78, 31, 81, 10, 52, 36],
        [63, 50, 66, 16, 75, 34, 94, 45, 19, 71],
        [39, 44, 91, 96, 11, 88, 86, 23, 63, 26],
        [ 2, 43, 66, 57, 55, 39, 85, 72, 69,  3],
        [16, 97, 30, 60, 70, 60, 71, 92, 43, 70],
        [38, 61, 32, 72, 50, 95, 87, 30, 99, 12],
        [11, 68, 72, 36, 95, 54, 29, 20, 53, 50],
        [71, 76, 23, 37, 99, 66, 19, 56, 28,  8]])

Create a multi-dimensional Tensor from:

1. List of lists
2. List of Series
3. `numpy` matrix
4. `pandas` matrix

In [35]:
# List of lists
multi_lists = [[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]]]

torch.tensor(multi_lists).shape

torch.Size([3, 3, 3])

In [36]:
# List of Series

In [37]:
# numpy matrix/ndarray

In [38]:
# pandas matrix

# Tensor Indexing

What is a multi-dimesional (n-D) tensor?

1. A multi-dimesional tensor has matrix indicies
2. A matrix has vector indicies
3. A vector has scalar indicies

Let's look at this visually, starting with the vector we created, $\vec{v}$ `vector`.

In [39]:
print(vector.shape)
print(vector)

torch.Size([10])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### Vectors, Elements, and Scalars
$\vec{v}$ = \[0, 1, 2, 3, 4, 5, 6, 7, 8, 9\]

$\vec{v}$ has a shape of _m_ x _n_ = 10 rows, 1 column

__Plain English__:

- We have an array with 10 numbers
- The shape of the array is 10 rows x 1 column

__Explanation__:

- We're working with a vector with 10 elements.
- The elements are _scalars_ with values 0 - 9.

> __Elements__ in _linear algebra_ are also called entries, coefficients, or components.

> 1. Elements of a vector
2. Entries of a vector
3. Coefficients of a vector
4. Components of a vector

> They all mean the same thing!

> To explain this difference between _elements_ and _scalars_, let's imagine you're sitting down to a nice breakfast with your family. 

>There's pancakes, sausage, toast, yogurt, fruit, bacon, tea, coffee, orange juice, and water. Like a vulture, you circle each platter for the perfect piece and add it to your plate. Once you're finished you take a seat.

> 1. Your _plate is the vector_. It holds your delicious breakfast.
2. Each piece of fresh food you have on your plate is the _number of elements in your vector_.
3. The __name__ of each piece(s) (e.g. 3 strips of bacon, 2 pieces of fruit, 1 dallop of yogurt, 4 pancakes) are your _scalars_!

>Food for thought: You have a preference, the pieces on your plate are the direct result of weighted decisions _you make_.

> ## Let's setup our vector
> How many _elements_ do we have?
 
> 3 (bacon strips)

> 2 (pieces of fruit)

> 1 (dallop of yogurt)
 
> 4 (pancakes)

> \----------------------

> 10 (pieces of food)
 
>Let's weight each food item:
- Bacon - 6
- Fruit - 9
- Yogurt - 10
- Pancakes - 11

>Let's make our plate:

>$\vec{plate}$ = \[6(bacon strip),
6(bacon strip),
6(bacon strip), 9(fruit), 9(fruit), 10(yogurt), 11(panacke), 11(pancake), 11(pancake), 11(pancake)\]

>Awesome. Let's not forget about our computer's breakfast, I mean _vector_:

>$\vec{v}$ = \[6, 6, 6, 9, 9, 10, 11, 11, 11, 11\]

> Help your family with the dishes :)

In [47]:
# Indexing into a vector results in a single value, our scalar.
# n is the number of elements in a vector, in our case 10
# ith element in vector is equal to v[i] here i=[1-1],....,i=[n-1]
# Here we get a scalar.
print(vector[0])
print(type(vector[0]))

tensor(0)
<class 'torch.Tensor'>


In [46]:
# To get a value, we need to pull the scalar out of the vector.
print(vector[0].item())
type(vector[0].item())

0


int

### Matrices and Vectors

Let's see what our matrix looks like

In [54]:
print(type(matrix_A))
print(matrix_A.ndim, 'dimensions')
print(matrix_A.shape)
print(matrix_A)

<class 'numpy.ndarray'>
2 dimensions
(3, 3)
[[9.6161819  9.65057624 4.98202805]
 [6.70362615 4.27509393 2.84638953]
 [3.91337981 1.09353844 9.32885306]]


### Indexing into the Matrix, Neo

- notes to add properties of indexing into a Matrix: row-wise, column-wise
- shape of the returned indexes

In [66]:
# Indexing into our matrix using, well, index/bracket notation :D
# The bracket notation returns only column values in the first row
# print(matrix_A[0]) 
print(matrix_A[0,:])  # used explicit index notation
print(matrix_A[0].shape)

[9.6161819  9.65057624 4.98202805]
(3,)


In [67]:
# The bracket notation returns all rows, of the second column.
print(matrix_A[:,1].shape)
print(matrix_A[:,1])

(3,)
[9.65057624 4.27509393 1.09353844]


Tests

In [27]:
# torch.tensor?

In [23]:
a = pd.Series(np.arange(0, 10))

# torch.tensor((a, b, c).as_matrix())
# torch.cat((a, b, c))

torch.tensor(a)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

``` python
np.ndarray(vector) # tensors do not support indexing error.
np.array(vector)
pd.Series(vector)
pd.DataFrame(vector)
```

In [24]:
T = torch.arange(0, 10_000_000).reshape(1000, 100, 100)
M = np.arange(0, 10_000_000).reshape(1000, 100, 100)

In [25]:
%%timeit -r 10 -n 1_000
1 + T

16.2 ms ± 491 µs per loop (mean ± std. dev. of 10 runs, 1000 loops each)


In [26]:
%%timeit -r 10 -n 1_000
1 + M

16.5 ms ± 282 µs per loop (mean ± std. dev. of 10 runs, 1000 loops each)
